# **Web Scraping & Data Handling Challenge**



### **Website:**
JustWatch -  https://www.justwatch.com/in/movies?release_year_from=2000


### **Description:**

JustWatch is a popular platform that allows users to search for movies and TV shows across multiple streaming services like Netflix, Amazon Prime, Hulu, etc. For this assignment, you will be required to scrape movie and TV show data from JustWatch using Selenium, Python, and BeautifulSoup. Extract data from HTML, not by directly calling their APIs. Then, perform data filtering and analysis using Pandas, and finally, save the results to a CSV file.

### **Tasks:**

**1. Web Scraping:**

Use BeautifulSoup to scrape the following data from JustWatch:

   **a. Movie Information:**

      - Movie title
      - Release year
      - Genre
      - IMDb rating
      - Streaming services available (Netflix, Amazon Prime, Hulu, etc.)
      - URL to the movie page on JustWatch

   **b. TV Show Information:**

      - TV show title
      - Release year
      - Genre
      - IMDb rating
      - Streaming services available (Netflix, Amazon Prime, Hulu, etc.)
      - URL to the TV show page on JustWatch

  **c. Scope:**

```
 ` - Scrape data for at least 50 movies and 50 TV shows.
   - You can choose the entry point (e.g., starting with popular movies,
     or a specific genre, etc.) to ensure a diverse dataset.`

```


**2. Data Filtering & Analysis:**

   After scraping the data, use Pandas to perform the following tasks:

   **a. Filter movies and TV shows based on specific criteria:**

   ```
      - Only include movies and TV shows released in the last 2 years (from the current date).
      - Only include movies and TV shows with an IMDb rating of 7 or higher.
```

   **b. Data Analysis:**

   ```
      - Calculate the average IMDb rating for the scraped movies and TV shows.
      - Identify the top 5 genres that have the highest number of available movies and TV shows.
      - Determine the streaming service with the most significant number of offerings.
      
   ```   

**3. Data Export:**

```
   - Dump the filtered and analysed data into a CSV file for further processing and reporting.

   - Keep the CSV file in your Drive Folder and Share the Drive link on the colab while keeping view access with anyone.
```

**Submission:**
```
- Submit a link to your Colab made for the assignment.

- The Colab should contain your Python script (.py format only) with clear
  comments explaining the scraping, filtering, and analysis process.

- Your Code shouldn't have any errors and should be executable at a one go.

- Before Conclusion, Keep your Dataset Drive Link in the Notebook.
```



**Note:**

1. Properly handle errors and exceptions during web scraping to ensure a robust script.

2. Make sure your code is well-structured, easy to understand, and follows Python best practices.

3. The assignment will be evaluated based on the correctness of the scraped data, accuracy of data filtering and analysis, and the overall quality of the Python code.

# **Start The Project**

## **Task 1:- Web Scrapping**

In [ ]:
#Installing all necessary labraries
!pip install bs4
!pip install requests

Requirement already satisfied: bs4 in /usr/local/lib/python3.10/dist-packages (0.0.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from bs4) (4.12.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->bs4) (2.6)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests) (2024.8.30)

In [ ]:
#import all necessary labraries
import requests
from bs4 import BeautifulSoup
import re
import pandas as pd
import numpy as np

## **Scrapping Movies Data**

In [ ]:
def fetch_movie_urls(url):
  response = requests.get(url, headers=headers)
  if response.status_code != 200:
    return "Failed to retrieve the page, status code:", response.status_code
  soup = BeautifulSoup(response.text, 'html.parser')
  return soup

headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36'
}


url = 'https://www.justwatch.com/in/movies?release_year_from=2000'
soup=fetch_movie_urls(url)
print(soup.prettify())

## Hint : Use the following code to extract the film urls
# movie_links = soup.find_all('a', href=True)
# movie_urls = [link['href'] for link in movie_links if '/movie/' in link['href']]

# url_list=[]
# for x in movie_urls:
#   url_list.append('https://www.justwatch.com'+x)

<!DOCTYPE html>
<html data-vue-meta="%7B%22dir%22:%7B%22ssr%22:%22ltr%22%7D,%22lang%22:%7B%22ssr%22:%22en%22%7D%7D" data-vue-meta-server-rendered="" dir="ltr" lang="en">
 <head>
  <meta charset="utf-8"/>
  <meta content="IE=edge" http-equiv="X-UA-Compatible"/>
  <meta charset="utf-8" data-vue-meta="ssr"/>
  <meta content="IE=edge" data-vue-meta="ssr" httpequiv="X-UA-Compatible"/>
  <meta content="viewport-fit=cover, width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" data-vue-meta="ssr" name="viewport"/>
  <meta content="JustWatch" data-vue-meta="ssr" property="og:site_name"/>
  <meta content="794243977319785" data-vue-meta="ssr" property="fb:app_id"/>
  <meta content="/appassets/img/JustWatch_logo_with_claim.png" data-vmid="og:image" data-vue-meta="ssr" property="og:image"/>
  <meta content="606" data-vmid="og:image:width" data-vue-meta="ssr" property="og:image:width"/>
  <meta content="302" data-vmid="og:image:height" data-vue-meta="ssr" property="og:image:height"/>
  <meta content="yes" data-vue-meta="ssr" name="mobile-web-app-capable"/>
  <meta content="yes" data-vue-meta="ssr" name="apple-mobile-web-app-capable"/>
  <meta content="#182531" data-vue-meta="ssr" name="theme-color"/>
  <meta content="AkO0-dINGfhSod2X6LeYIp9hwZc8ShczjzJA2a47dME" data-vue-meta="ssr" name="google-site-verification"/>
  <meta content="d61y4roe8t5xwbb0gfu6gwe8j8iq3i" data-vue-meta="ssr" name="facebook-domain-verification"/>
  <meta content="dmorpwc4h544ct6mv" data-vue-meta="ssr" name="dailymotion-domain-verification"/>
  <meta content="dmm2vwzsugkzg13q5" data-vue-meta="ssr" name="dailymotion-domain-verification"/>
  <meta content="Watch movies online" data-vmid="og:title" data-vue-meta="ssr" property="og:title"/>
  <meta content="movies, watch online, streaming, rental, download" data-vue-meta="ssr" name="keywords"/>
  <meta content="Where to watch movies online? Find with JustWatch all the movies you can watch online on Netflix, iflix, Hooq and 4 other streaming providers. Purchase, rent online &amp; flat-rate." data-vmid="description" data-vue-meta="ssr" name="description"/>
  <meta content="Where to watch movies online? Find with JustWatch all the movies you can watch online on Netflix, iflix, Hooq and 4 other streaming providers. Purchase, rent online &amp; flat-rate." data-vmid="og:description" data-vue-meta="ssr" property="og:description"/>
  <meta content="https://www.justwatch.com/in/movies" data-vmid="og:url" data-vue-meta="ssr" property="og:url"/>
  <meta content="noindex, follow" data-vmid="robots" data-vue-meta="ssr" name="robots"/>
  <title>
   Watch movies online
  </title>
  <link as="font" crossorigin="true" data-vue-meta="ssr" href="/appassets/fonts/lato-regular.woff2" rel="preload" type="font/woff2"/>
  <link as="font" crossorigin="true" data-vue-meta="ssr" href="/appassets/fonts/lato-700.woff2" rel="preload" type="font/woff2"/>
  <link as="font" crossorigin="true" data-vue-meta="ssr" href="/appassets/fonts/lato-900.woff2" rel="preload" type="font/woff2"/>
  <link data-vue-meta="ssr" href="/appassets/favicon.ico" rel="icon"/>
  <link data-vue-meta="ssr" href="https://www.googletagmanager.com/" rel="dns-prefetch"/>
  <link data-vue-meta="ssr" href="https://ib.adnxs.com" rel="dns-prefetch"/>
  <link data-vmid="canonical" data-vue-meta="ssr" href="https://www.justwatch.com/in/movies" rel="canonical"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/ar/peliculas" hreflang="es-AR" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/at/Filme" hreflang="de-AT" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/au/movies" hreflang="en-AU" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/be/films" hreflang="fr-BE" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/bg/филми" hreflang="bg-BG" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/br/filmes" hreflang="pt-BR" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/ca/movies" hreflang="en-CA" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/ch/Filme" hreflang="de-CH" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/cl/peliculas" hreflang="es-CL" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/co/peliculas" hreflang="es-CO" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/cz/filmy" hreflang="cs-CZ" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/de/Filme" hreflang="de-DE" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/dk/movies" hreflang="en-DK" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/ec/peliculas" hreflang="es-EC" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/eg/movies" hreflang="ar-EG" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/es/peliculas" hreflang="es-ES" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/fi/elokuvat" hreflang="fi-FI" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/fr/films" hreflang="fr-FR" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/uk/movies" hreflang="en-GB" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/gr/ταινίες" hreflang="el-GR" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/hk/電影" hreflang="zh-HK" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/hr/filmovi" hreflang="hr-HR" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/hu/filmek" hreflang="hu-HU" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/ie/movies" hreflang="en-IE" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/in/movies" hreflang="en-IN" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/iq/movies" hreflang="ar-IQ" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/is/kvikmyndir" hreflang="is-IS" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/it/film" hreflang="it-IT" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/jp/映画" hreflang="ja-JP" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/kr/영화" hreflang="ko-KR" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/lb/movies" hreflang="ar-LB" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/mx/peliculas" hreflang="es-MX" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/my/movies" hreflang="en-MY" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/nl/movies" hreflang="en-NL" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/no/movies" hreflang="en-NO" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/nz/movies" hreflang="en-NZ" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/pe/peliculas" hreflang="es-PE" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/ph/movies" hreflang="en-PH" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/pl/filmy" hreflang="pl-PL" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/ps/movies" hreflang="ar-PS" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/pt/filmes" hreflang="pt-PT" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/ro/filme" hreflang="ro-RO" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/ru/фильмы" hreflang="ru-RU" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/se/filmer" hreflang="sv-SE" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/sg/movies" hreflang="en-SG" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/sk/filmy" hreflang="sk-SK" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/tr/filmler" hreflang="tr-TR" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/us/movies" hreflang="en-US" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/va/film" hreflang="it-VA" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/xk/filmat" hreflang="sq-XK" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/za/movies" hreflang="en-ZA" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/ee/filmid" hreflang="et-EE" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/lt/filmai" hreflang="lt-LT" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/id/movies" hreflang="en-ID" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/th/movies" hreflang="en-TH" rel="alternate"/>
  <link data-vue-meta="ssr" href="https://www.justwatch.com/tw/電影" hreflang="zh-TW" rel="alternate"/>
  <base href="/" target="_self"/>
  <link as="image" href="/appassets/img/logo/JustWatch-logo-large.webp" imagesrcset="/appassets/img/logo/JustWatch-logo-large.webp 1px" importance="high" rel="preload"/>
  <link as="image" href="https://www.justwatch.com/images/icon/207360008/s100/netflix.{format}/icon.webp" imagesrcset="https://www.justwatch.com/images/icon/207360008/s100/netflix.{format}/icon.webp 1px" importance="high" media="(min-width: 0px)" rel="preload"/>
  <link as="image" href="https://www.justwatch.com/images/icon/52449861/s100/amazonprimevideo.{format}/icon.webp" imagesrcset="https://www.justwatch.com/images/icon/52449861/s100/amazonprimevideo.{format}/icon.webp 1px" importance="high" media="(min-width: 0px)" rel="preload"/>
  <link as="image" href="https://www.justwatch.com/images/icon/152862153/s100/appletvplus.{format}/icon.webp" imagesrcset="https://www.justwatch.com/images/icon/152862153/s100/appletvplus.{format}/icon.webp 1px" importance="high" media="(min-width: 0px)" rel="preload"/>
  <link as="image" href="https://www.justwatch.com/images/icon/190848813/s100/itunes.{format}/icon.webp" imagesrcset="https://www.justwatch.com/images/icon/190848813/s100/itunes.{format}/icon.webp 1px" importance="high" media="(min-width: 0px)" rel="preload"/>
  <link as="image" href="https://www.justwatch.com/images/icon/127445869/s100/crunchyroll.{format}/icon.webp" imagesrcset="https://www.justwatch.com/images/icon/127445869/s100/crunchyroll.{format}/icon.webp 1px" importance="high" media="(min-width: 0px)" rel="preload"/>
  <link as="image" href="https://www.justwatch.com/images/icon/240029443/s100/hotstar.{format}/icon.webp" imagesrcset="https://www.justwatch.com/images/icon/240029443/s100/hotstar.{format}/icon.webp 1px" importance="high" media="(min-width: 0px)" rel="preload"/>
  <link as="image" href="https://www.justwatch.com/images/icon/312325227/s100/jiocinema.{format}/icon.webp" imagesrcset="https://www.justwatch.com/images/icon/312325227/s100/jiocinema.{format}/icon.webp 1px" importance="high" media="(min-width: 0px)" rel="preload"/>
  <link as="image" href="https://www.justwatch.com/images/poster/321212658/s332/bhool-bhulaiyaa-3.webp" imagesrcset="https://www.justwatch.com/images/poster/321212658/s332/bhool-bhulaiyaa-3.webp 1px, https://www.justwatch.com/images/poster/321212658/s332/bhool-bhulaiyaa-3.webp" importance="high" rel="preload"/>
  <link as="image" href="https://www.justwatch.com/images/poster/321157287/s332/stree-2.webp" imagesrcset="https://www.justwatch.com/images/poster/321157287/s332/stree-2.webp 1px, https://www.justwatch.com/images/poster/321157287/s332/stree-2.webp" importance="high" rel="preload"/>
  <link as="image" href="https://www.justwatch.com/images/poster/318387357/s332/deadpool-3.webp" imagesrcset="https://www.justwatch.com/images/poster/318387357/s332/deadpool-3.webp 1px, https://www.justwatch.com/images/poster/318387357/s332/deadpool-3.webp" importance="high" rel="preload"/>
  <link as="image" href="https://www.justwatch.com/images/poster/320520686/s332/the-substance.webp" imagesrcset="https://www.justwatch.com/images/poster/320520686/s332/the-substance.webp 1px, https://www.justwatch.com/images/poster/320520686/s332/the-substance.webp" importance="high" rel="preload"/>
  <style data-vue-ssr-id="16dee5de:0 16dee5de:1 374c0f88:0 61943ce6:0 c9008484:0 a55614a4:0 2922e121:0 275e282f:0 5fbc3e0a:0 6477115b:0 016f7854:0 2f594a84:0 07f6a070:0 1c1c7876:0 722b1bb4:0 89c5701e:0 2935cc78:0 18cad8ea:0 61d60340:0 93d5461c:0 3bdce1a2:0 0cd1495d:0 9df6854c:0 1d549892:0 772a1a34:0 75a9bc05:0 67f80acd:0 7a6fba76:0 692f787c:0 64954408:0 4c8f0d7c:0 1ccfd6a3:0 bdcde3be:0 90f1276c:0 6ba62192:0">
   html.ios{--ion-default-font:-apple-system,BlinkMacSystemFont,"Helvetica Neue","Roboto",sans-serif}html.md{--ion-default-font:"Roboto","Helvetica Neue",sans-serif}html{--ion-font-family:var(--ion-default-font)}body{background:var(--ion-background-color)}body.backdrop-no-scroll{overflow:hidden}html.ios ion-modal.modal-card .ion-page>ion-header>ion-toolbar:first-of-type{padding-top:0}html.ios ion-modal .ion-page{border-radius:inherit}.ion-color-primary{--ion-color-base:var(--ion-color-primary,#3880ff)!important;--ion-color-base-rgb:var(--ion-color-primary-rgb,56,128,255)!important;--ion-color-contrast:var(--ion-color-primary-contrast,#fff)!important;--ion-color-contrast-rgb:var(--ion-color-primary-contrast-rgb,255,255,255)!important;--ion-color-shade:var(--ion-color-primary-shade,#3171e0)!important;--ion-color-tint:var(--ion-color-primary-tint,#4c8dff)!important}.ion-color-secondary{--ion-color-base:var(--ion-color-secondary,#3dc2ff)!important;--ion-color-base-rgb:var(--ion-color-secondary-rgb,61,194,255)!important;--ion-color-contrast:var(--ion-color-secondary-contrast,#fff)!important;--ion-color-contrast-rgb:var(--ion-color-secondary-contrast-rgb,255,255,255)!important;--ion-color-shade:var(--ion-color-secondary-shade,#36abe0)!important;--ion-color-tint:var(--ion-color-secondary-tint,#50c8ff)!important}.ion-color-tertiary{--ion-color-base:var(--ion-color-tertiary,#5260ff)!important;--ion-color-base-rgb:var(--ion-color-tertiary-rgb,82,96,255)!important;--ion-color-contrast:var(--ion-color-tertiary-contrast,#fff)!important;--ion-color-contrast-rgb:var(--ion-color-tertiary-contrast-rgb,255,255,255)!important;--ion-color-shade:var(--ion-color-tertiary-shade,#4854e0)!important;--ion-color-tint:var(--ion-color-tertiary-tint,#6370ff)!important}.ion-color-success{--ion-color-base:var(--ion-color-success,#2dd36f)!important;--ion-color-base-rgb:var(--ion-color-success-rgb,45,211,111)!important;--ion-color-contrast:var(--ion-color-success-contrast,#fff)!important;--ion-color-contrast-rgb:var(--ion-color-success-contrast-rgb,255,255,255)!important;--ion-color-shade:var(--ion-color-success-shade,#28ba62)!important;--ion-color-tint:var(--ion-color-success-tint,#42d77d)!important}.ion-color-warning{--ion-color-base:var(--ion-color-warning,#ffc409)!important;--ion-color-base-rgb:var(--ion-color-warning-rgb,255,196,9)!important;--ion-color-contrast:var(--ion-color-warning-contrast,#000)!important;--ion-color-contrast-rgb:var(--ion-color-warning-contrast-rgb,0,0,0)!important;--ion-color-shade:var(--ion-color-warning-shade,#e0ac08)!important;--ion-color-tint:var(--ion-color-warning-tint,#ffca22)!important}.ion-color-danger{--ion-color-base:var(--ion-color-danger,#eb445a)!important;--ion-color-base-rgb:var(--ion-color-danger-rgb,235,68,90)!important;--ion-color-contrast:var(--ion-color-danger-contrast,#fff)!important;--ion-color-contrast-rgb:var(--ion-color-danger-contrast-rgb,255,255,255)!important;--ion-color-shade:var(--ion-color-danger-shade,#cf3c4f)!important;--ion-color-tint:var(--ion-color-danger-tint,#ed576b)!important}.ion-color-light{--ion-color-base:var(--ion-color-light,#f4f5f8)!important;--ion-color-base-rgb:var(--ion-color-light-rgb,244,245,248)!important;--ion-color-contrast:var(--ion-color-light-contrast,#000)!important;--ion-color-contrast-rgb:var(--ion-color-light-contrast-rgb,0,0,0)!important;--ion-color-shade:var(--ion-color-light-shade,#d7d8da)!important;--ion-color-tint:var(--ion-color-light-tint,#f5f6f9)!important}.ion-color-medium{--ion-color-base:var(--ion-color-medium,#92949c)!important;--ion-color-base-rgb:var(--ion-color-medium-rgb,146,148,156)!important;--ion-color-contrast:var(--ion-color-medium-contrast,#fff)!important;--ion-color-contrast-rgb:var(--ion-color-medium-contrast-rgb,255,255,255)!important;--ion-color-shade:var(--ion-color-medium-shade,#808289)!important;--ion-color-tint:var(--ion-color-medium-tint,#9d9fa6)!important}.ion-color-dark{--ion-color-base:var(--ion-color-dark,#222428)!important;--ion-color-base-rgb:var(--ion-color-dark-rgb,34,36,40)!important;--ion-color-contrast:var(--ion-color-dark-contrast,#fff)!important;--ion-color-contrast-rgb:var(--ion-color-dark-contrast-rgb,255,255,255)!important;--ion-color-shade:var(--ion-color-dark-shade,#1e2023)!important;--ion-color-tint:var(--ion-color-dark-tint,#383a3e)!important}.ion-page{left:0;right:0;top:0;bottom:0;display:flex;position:absolute;flex-direction:column;justify-content:space-between;contain:layout size style;overflow:hidden;z-index:0}.split-pane-visible>.ion-page.split-pane-main{position:relative}.ion-page-hidden,[hidden],ion-action-sheet-controller,ion-alert-controller,ion-loading-controller,ion-menu-controller,ion-modal-controller,ion-nav-controller,ion-picker-controller,ion-popover-controller,ion-route,ion-route-redirect,ion-router,ion-select-option,ion-toast-controller{display:none!important}.ion-page-invisible{opacity:0}.can-go-back>ion-header ion-back-button{display:block}html.plt-ios.plt-hybrid,html.plt-ios.plt-pwa{--ion-statusbar-padding:20px}@supports(padding-top:20px){html{--ion-safe-area-top:var(--ion-statusbar-padding)}}@supports(padding-top:constant(safe-area-inset-top)){html{--ion-safe-area-top:constant(safe-area-inset-top);--ion-safe-area-bottom:constant(safe-area-inset-bottom);--ion-safe-area-left:constant(safe-area-inset-left);--ion-safe-area-right:constant(safe-area-inset-right)}}@supports(padding-top:env(safe-area-inset-top)){html{--ion-safe-area-top:env(safe-area-inset-top);--ion-safe-area-bottom:env(safe-area-inset-bottom);--ion-safe-area-left:env(safe-area-inset-left);--ion-safe-area-right:env(safe-area-inset-right)}}ion-card-header.ion-color .ion-inherit-color,ion-card.ion-color .ion-inherit-color{color:inherit}.menu-content{transform:translateZ(0)}.menu-content-open{cursor:pointer;touch-action:manipulation;pointer-events:none}.ios .menu-content-reveal{box-shadow:-8px 0 42px rgba(0,0,0,.08)}[dir=rtl].ios .menu-content-reveal{box-shadow:8px 0 42px rgba(0,0,0,.08)}.md .menu-content-push,.md .menu-content-reveal{box-shadow:4px 0 16px rgba(0,0,0,.18)}
/*!
 * Bootstrap v3.3.7 (http://getbootstrap.com)
 * Copyright 2011-2016 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)

## **Fetching Movie URL's**

In [ ]:
# Write Your Code here
movie_url = []
for i in soup.find_all('a', class_ = 'title-list-grid__item--link'):
  movie_url.append('https://www.justwatch.com' +i['href'])
print(movie_url)
print(f'Total number of Movie is {len(movie_url)}')

['https://www.justwatch.com/in/movie/bhool-bhulaiyaa-3', 'https://www.justwatch.com/in/movie/stree-2', 'https://www.justwatch.com/in/movie/deadpool-3', 'https://www.justwatch.com/in/movie/the-substance', 'https://www.justwatch.com/in/movie/meiyazhagan', 'https://www.justwatch.com/in/movie/ntr-30', 'https://www.justwatch.com/in/movie/vettaiyan', 'https://www.justwatch.com/in/movie/venom-3-2024', 'https://www.justwatch.com/in/movie/do-patti', 'https://www.justwatch.com/in/movie/kishkkindha-kandam', 'https://www.justwatch.com/in/movie/the-wild-robot', 'https://www.justwatch.com/in/movie/siddharth-roy', 'https://www.justwatch.com/in/movie/singham-again-2024-0', 'https://www.justwatch.com/in/movie/lubber-pandhu', 'https://www.justwatch.com/in/movie/gladiator', 'https://www.justwatch.com/in/movie/gaganachari', 'https://www.justwatch.com/in/movie/black-2024', 'https://www.justwatch.com/in/movie/furiosa', 'https://www.justwatch.com/in/movie/amaran-2024', 'https://www.justwatch.com/in/movie/martin', 'https://www.justwatch.com/in/movie/khel-khel-mein', 'https://www.justwatch.com/in/movie/venom-2018', 'https://www.justwatch.com/in/movie/thalapathy-68', 'https://www.justwatch.com/in/movie/alien-romulus', 'https://www.justwatch.com/in/movie/ajayante-randam-moshanam', 'https://www.justwatch.com/in/movie/kill-2024', 'https://www.justwatch.com/in/movie/longlegs', 'https://www.justwatch.com/in/movie/transformers-one-2024', 'https://www.justwatch.com/in/movie/strange-darling', 'https://www.justwatch.com/in/movie/tumbbad', 'https://www.justwatch.com/in/movie/the-buckingham-murders', 'https://www.justwatch.com/in/movie/swag', 'https://www.justwatch.com/in/movie/vicky-vidya-ka-woh-wala-video', 'https://www.justwatch.com/in/movie/untitled-soorarai-pottru-remake', 'https://www.justwatch.com/in/movie/kalki-2898-ad', 'https://www.justwatch.com/in/movie/lucky-baskhar', 'https://www.justwatch.com/in/movie/bhool-bhulaiyaa-2', 'https://www.justwatch.com/in/movie/venom-let-there-be-carnage', 'https://www.justwatch.com/in/movie/it-ends-with-us', 'https://www.justwatch.com/in/movie/vedaa', 'https://www.justwatch.com/in/movie/vaazhai', 'https://www.justwatch.com/in/movie/thangalaan', 'https://www.justwatch.com/in/movie/golam', 'https://www.justwatch.com/in/movie/zwigato', 'https://www.justwatch.com/in/movie/munjha', 'https://www.justwatch.com/in/movie/viswam-2024', 'https://www.justwatch.com/in/movie/saripodhaa-sanivaaram', 'https://www.justwatch.com/in/movie/bhool-bhulaiyaa', 'https://www.justwatch.com/in/movie/salaar', 'https://www.justwatch.com/in/movie/pushpa', 'https://www.justwatch.com/in/movie/my-old-ass', 'https://www.justwatch.com/in/movie/365-days', 'https://www.justwatch.com/in/movie/yudhra', 'https://www.justwatch.com/in/movie/kanguva', 'https://www.justwatch.com/in/movie/stree', 'https://www.justwatch.com/in/movie/caddo-lake', 'https://www.justwatch.com/in/movie/je-jatt-vigad-gya', 'https://www.justwatch.com/in/movie/level-cross', 'https://www.justwatch.com/in/movie/speak-no-evil-2024', 'https://www.justwatch.com/in/movie/dont-move', 'https://www.justwatch.com/in/movie/despicable-me-4-2024', 'https://www.justwatch.com/in/movie/laila-majnu', 'https://www.justwatch.com/in/movie/premalu', 'https://www.justwatch.com/in/movie/jigra-2024', 'https://www.justwatch.com/in/movie/k-g-f-chapter-1', 'https://www.justwatch.com/in/movie/96', 'https://www.justwatch.com/in/movie/animal-2022', 'https://www.justwatch.com/in/movie/super-deluxe', 'https://www.justwatch.com/in/movie/woman-of-the-hour', 'https://www.justwatch.com/in/movie/oldboy-2003', 'https://www.justwatch.com/in/movie/smile-2', 'https://www.justwatch.com/in/movie/mathu-vadalara', 'https://www.justwatch.com/in/movie/apocalypse-z-el-principio-del-fin', 'https://www.justwatch.com/in/movie/fifty-shades-of-grey', 'https://www.justwatch.com/in/movie/time-cut', 'https://www.justwatch.com/in/movie/loups-garous', 'https://www.justwatch.com/in/movie/aavesham-2024', 'https://www.justwatch.com/in/movie/the-fall-guy', 'https://www.justwatch.com/in/movie/vivekanandan-viralaanu', 'https://www.justwatch.com/in/movie/k-g-f-chapter-2', 'https://www.justwatch.com/in/movie/the-gangster-the-cop-the-devil', 'https://www.justwatch.com/in/movie/smile-2022-0', 'https://www.justwatch.com/in/movie/dune-part-two', 'https://www.justwatch.com/in/movie/harry-potter-and-the-philosophers-stone', 'https://www.justwatch.com/in/movie/bagheera-2024', 'https://www.justwatch.com/in/movie/a-quiet-place-day-one', 'https://www.justwatch.com/in/movie/joker-2', 'https://www.justwatch.com/in/movie/maa-nanna-superhero', 'https://www.justwatch.com/in/movie/maharaja-2024', 'https://www.justwatch.com/in/movie/the-sabarmati-report', 'https://www.justwatch.com/in/movie/challengers', 'https://www.justwatch.com/in/movie/bramayugam', 'https://www.justwatch.com/in/movie/kadaisi-ulaga-por', 'https://www.justwatch.com/in/movie/inside-out-2', 'https://www.justwatch.com/in/movie/nandhan', 'https://www.justwatch.com/in/movie/subservience', 'https://www.justwatch.com/in/movie/hanu-man', 'https://www.justwatch.com/in/movie/millers-girl', 'https://www.justwatch.com/in/movie/double-ismart', 'https://www.justwatch.com/in/movie/haikyu-the-movie-decisive-battle-at-the-garbage-dump']
Total number of Movie is 100

## **Scrapping Movie Title**

In [ ]:
movie_title = []
for url in movie_url:
  try:
    content = requests.get(url,headers = headers)
    soup = BeautifulSoup(content.text,'html.parser')
    title = soup.find_all('h1')[0].text
  except:
    title = 'NA'
  movie_title.append(title)
print(movie_title)
print('Total number of title is' , len(movie_title))

[' Bhool Bhulaiyaa 3 (2024)', ' Stree 2: Sarkate Ka Aatank (2024)', ' Deadpool & Wolverine (2024)', ' The Substance (2024)', ' Meiyazhagan (2024)', ' Devara Part 1 (2024)', ' Vettaiyan (2024)', ' Venom: The Last Dance (2024)', ' Do Patti (2024)', ' Kishkindha Kaandam (2024)', ' The Wild Robot (2024)', ' Siddharth Roy (2024)', ' Singham Again (2024)', ' Lubber Pandhu (2024)', ' Gladiator (2000)', ' Gaganachari (2024)', ' Black (2024)', ' Furiosa: A Mad Max Saga (2024)', ' Amaran (2024)', ' Martin (2024)', ' Khel Khel Mein (2024)', ' Venom (2018)', ' The Greatest of All Time (2024)', ' Alien: Romulus (2024)', ' A.R.M (2024)', ' Kill (2024)', ' Longlegs (2024)', ' Transformers One (2024)', ' Strange Darling (2024)', ' Tumbbad (2018)', ' The Buckingham Murders (2024)', ' Swag (2024)', ' Vicky Vidya Ka Woh Wala Video (2024)', ' Sarfira (2024)', ' Kalki 2898 AD (2024)', ' Lucky Baskhar (2024)', ' Bhool Bhulaiyaa 2 (2022)', ' Venom: Let There Be Carnage (2021)', ' It Ends with Us (2024)', ' Vedaa (2024)', ' Vaazhai (2024)', ' Thangalaan (2024)', ' Golam (2024)', ' Zwigato (2023)', ' Munjya (2024)', ' Viswam (2024)', ' Saripodhaa Sanivaaram (2024)', ' Bhool Bhulaiyaa (2007)', ' Salaar (2023)', ' Pushpa: The Rise - Part 1 (2021)', ' My Old Ass (2024)', ' 365 Days (2020)', ' Yudhra (2024)', ' Kanguva (2024)', ' Stree (2018)', ' Caddo Lake (2024)', ' Je Jatt Vigad Gya (2024)', ' Level Cross (2024)', ' Speak No Evil (2024)', " Don't Move (2024)", ' Despicable Me 4 (2024)', ' Laila Majnu (2018)', ' Premalu (2024)', ' Jigra (2024)', ' K.G.F: Chapter 1 (2018)', ' 96 (2018)', ' Animal (2023)', ' Super Deluxe (2019)', ' Woman of the Hour (2024)', ' Oldboy (2003)', ' Smile 2 (2024)', ' Mathu Vadalara (2019)', ' Apocalypse Z: The Beginning of the End (2024)', ' Fifty Shades of Grey (2015)', ' Time Cut (2024)', ' Family Pack (2024)', ' Aavesham (2024)', ' The Fall Guy (2024)', ' Vivekanandan Viralaanu (2024)', ' K.G.F: Chapter 2 (2022)', ' The Gangster, the Cop, the Devil (2019)', ' Smile (2022)', ' Dune: Part Two (2024)', " Harry Potter and the Philosopher's Stone (2001)", ' Bagheera (2024)', ' A Quiet Place: Day One (2024)', ' Joker: Folie à Deux (2024)', ' Maa Nanna Superhero (2024)', ' Maharaja (2024)', ' The Sabarmati Report (2024)', ' Challengers (2024)', ' Bramayugam (2024)', ' Kadaisi Ulaga Por (2024)', ' Inside Out 2 (2024)', ' Nandhan (2024)', ' Subservience (2024)', ' Hanu-Man (2024)', " Miller's Girl (2024)", ' Double Ismart (2024)', ' HAIKYU!! The Dumpster Battle (2024)']
Total number of title is 100

## **Scrapping release Year**

In [ ]:
# Write Your Code here
movie_year = []
for url in movie_url:
  try:
    content = requests.get(url,headers = headers)
    soup = BeautifulSoup(content.text, 'html.parser')
    year = soup.find_all('span' , class_= 'release-year')[0].text.strip('()')
  except:
    year = 'NA'
  movie_year.append(year)
print(movie_year)
print('Total number of movie:', len(movie_year))

['2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2000', '2024', '2024', '2024', '2024', '2024', '2024', '2018', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2018', '2024', '2024', '2024', '2024', '2024', '2024', '2022', '2021', '2024', '2024', '2024', '2024', '2024', '2023', '2024', '2024', '2024', '2007', '2023', '2021', '2024', '2020', '2024', '2024', '2018', '2024', '2024', '2024', '2024', '2024', '2024', '2018', '2024', '2024', '2018', '2018', '2023', '2019', '2024', '2003', '2024', '2019', '2024', '2015', '2024', '2024', '2024', '2024', '2024', '2022', '2019', '2022', '2024', '2001', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024', '2024']
Total number of movie: 100

## **Scrapping Genres**

In [ ]:
movie_genres = []
for url in movie_url:
  try:
    content = requests.get(url,headers = headers)
    soup = BeautifulSoup(content.text,'html.parser')
    for i in soup.find_all('div', class_ = 'detail-infos'):
      if i.find_all('h3')[0].text == 'Genres':
        genres = i.find_all('span')[0].text
  except:
    genres = 'NA'
  movie_genres.append(genres)
print(movie_genres)
print(f'Total number of genres is : {len(movie_genres)}')

['Comedy, Horror', 'Comedy, Horror', 'Comedy, Science-Fiction, Action & Adventure', 'Horror, Science-Fiction, Drama', 'Kids & Family, Drama', 'Action & Adventure, Drama, Mystery & Thriller', 'Crime, Drama, Action & Adventure', 'Action & Adventure, Science-Fiction, Mystery & Thriller', 'Mystery & Thriller, Drama, Crime', 'Drama, Mystery & Thriller', 'Animation, Science-Fiction', 'Drama, Romance', 'Action & Adventure, Drama', 'Comedy, Drama, Sport, Kids & Family, Romance', 'Action & Adventure, Drama', 'Fantasy, Science-Fiction, Comedy', 'Mystery & Thriller, Horror, Science-Fiction', 'Action & Adventure, Science-Fiction, Mystery & Thriller', 'Action & Adventure, Drama, War & Military', 'Action & Adventure, Drama, Mystery & Thriller', 'Drama, Comedy', 'Science-Fiction, Action & Adventure', 'Action & Adventure, Drama, Mystery & Thriller', 'Science-Fiction, Horror, Mystery & Thriller', 'Action & Adventure, Drama, Comedy', 'Drama, Mystery & Thriller, Action & Adventure, Crime', 'Mystery & Thriller, Crime, Horror', 'Science-Fiction, Animation, Action & Adventure, Kids & Family, Fantasy', 'Horror, Mystery & Thriller, Crime', 'Fantasy, Horror, Mystery & Thriller, Drama, Made in Europe', 'Drama, Crime, Mystery & Thriller', 'Comedy, Drama', 'Comedy', 'Drama', 'Drama, Fantasy, Science-Fiction, Mystery & Thriller, Action & Adventure', 'Crime, Drama, Mystery & Thriller', 'Horror, Comedy', 'Science-Fiction, Action & Adventure, Mystery & Thriller', 'Drama, Romance', 'Action & Adventure, Drama, Mystery & Thriller', 'Drama, Kids & Family', 'Action & Adventure, Fantasy, History, Drama', 'Crime', 'Drama', 'Comedy, Horror', 'Action & Adventure, Comedy, Mystery & Thriller', 'Action & Adventure, Mystery & Thriller, Drama', 'Horror, Mystery & Thriller, Comedy', 'Crime, Drama, Mystery & Thriller, Action & Adventure', 'Drama, Mystery & Thriller, Action & Adventure, Crime', 'Comedy, Drama, Romance, Science-Fiction', 'Drama, Romance, Made in Europe', 'Mystery & Thriller, Action & Adventure, Drama', 'Mystery & Thriller, Fantasy, Action & Adventure, Drama', 'Horror, Comedy, Drama', 'Drama, Mystery & Thriller, Science-Fiction, Horror', 'Drama', 'Drama, Mystery & Thriller', 'Horror, Mystery & Thriller, Drama', 'Mystery & Thriller, Horror', 'Comedy, Action & Adventure, Animation, Kids & Family, Crime, Science-Fiction', 'Romance, Drama', 'Comedy, Romance', 'Crime, Drama, Mystery & Thriller, Action & Adventure', 'Mystery & Thriller, Action & Adventure, Crime, Drama', 'Romance, Drama', 'Action & Adventure, Crime, Drama, Mystery & Thriller', 'Mystery & Thriller, Drama, Crime, Comedy', 'Crime, Drama, Mystery & Thriller', 'Drama, Mystery & Thriller, Action & Adventure', 'Horror, Mystery & Thriller', 'Crime, Comedy, Mystery & Thriller', 'Action & Adventure, Horror, Science-Fiction, Mystery & Thriller, Drama', 'Romance, Mystery & Thriller, Drama', 'Science-Fiction, Mystery & Thriller, Horror', 'Comedy, Fantasy', 'Action & Adventure, Comedy', 'Action & Adventure, Comedy, Drama, Romance', 'Comedy, Drama', 'Crime, Drama, Mystery & Thriller, Action & Adventure', 'Crime, Action & Adventure, Mystery & Thriller', 'Horror, Mystery & Thriller', 'Science-Fiction, Action & Adventure, Drama', 'Action & Adventure, Fantasy, Kids & Family', 'Mystery & Thriller, Action & Adventure', 'Science-Fiction, Mystery & Thriller, Drama, Horror', 'Drama, Mystery & Thriller, Crime', 'Drama', 'Crime, Drama, Mystery & Thriller, Action & Adventure', 'Mystery & Thriller, Drama', 'Drama, Romance, Sport, Comedy', 'Drama, Horror, Mystery & Thriller', 'Science-Fiction, Mystery & Thriller', 'Kids & Family, Action & Adventure, Comedy, Drama, Animation, Fantasy', 'Drama', 'Science-Fiction, Mystery & Thriller, Horror', 'Fantasy, Action & Adventure, Comedy, Science-Fiction', 'Mystery & Thriller, Comedy, Drama', 'Action & Adventure, Science-Fiction, Mystery & Thriller', 'Drama, Sport, Animation, Comedy']
Total number of genres is : 100

## **Scrapping IMBD Rating**

In [ ]:
# Write Your Code here
imdb_rating = []
for url in movie_url:
  try:
    content = requests.get(url, headers = headers)
    soup = BeautifulSoup(content.text,'html.parser')
    for i in soup.find_all('div', class_ = 'detail-infos'):
      if i.find_all('h3')[0].text =='Rating':
        rating = i.find_all('div')[0].text.strip().split()[0]
  except:
    rating = 'NA'
  imdb_rating.append(rating)
print(imdb_rating)
print(f'Number of imdb_rating is : {len(imdb_rating)}')

['8.4', '7.0', '7.7', '7.5', '8.4', '6.1', '7.5', '7.5', '6.7', '8.5', '8.5', '6.7', '6.7', '8.3', '8.5', '7.1', '7.2', '7.5', '7.5', '2.6', '6.6', '6.6', '5.8', '7.2', '7.3', '7.6', '6.7', '6.7', '7.1', '7.1', '6.2', '7.8', '7.8', '7.2', '7.1', '7.1', '5.7', '5.9', '6.5', '6.0', '7.8', '7.8', '7.2', '7.0', '6.4', '4.3', '7.0', '7.5', '6.6', '7.6', '7.0', '3.3', '5.4', '5.4', '7.5', '6.9', '5.2', '6.8', '6.8', '5.8', '6.2', '7.7', '7.8', '7.8', '7.8', '8.5', '6.1', '8.2', '6.6', '8.3', '8.3', '8.2', '6.1', '4.2', '5.0', '5.5', '7.8', '6.9', '4.0', '8.2', '7.0', '7.0', '8.5', '7.6', '7.8', '6.3', '6.3', '7.0', '8.5', '8.5', '7.1', '7.8', '6.3', '7.6', '8.3', '8.3', '7.8', '5.2', '2.9', '2.9']
Number of imdb_rating is : 100

## **Scrapping Runtime/Duration**

In [ ]:
# Write Your Code here
movie_runtime = []
for url in movie_url:
  try:
    content = requests.get(url,headers = headers)
    soup = BeautifulSoup(content.text,'html.parser')
    for i in soup.find_all('div',class_ = 'detail-infos'):
      if i.find_all('h3')[0].text == 'Runtime':
        runtime = i.find_all('div')[0].text
  except:
    runtime = 'NA'
  movie_runtime.append(runtime)
print(movie_runtime)
print('The number of runtime :' , len(movie_runtime))

['2h 38min', '2h 27min', '2h 8min', '2h 21min', '2h 57min', '2h 56min', '2h 43min', '1h 50min', '2h 7min', '2h 13min', '1h 42min', '2h 28min', '2h 24min', '2h 26min', '2h 35min', '1h 54min', '2h 30min', '2h 28min', '2h 47min', '2h 27min', '2h 15min', '1h 52min', '3h 3min', '1h 59min', '2h 27min', '1h 45min', '1h 41min', '1h 44min', '1h 37min', '1h 44min', '1h 47min', '2h 30min', '2h 32min', '2h 35min', '3h 0min', '2h 50min', '2h 23min', '1h 37min', '2h 10min', '2h 25min', '2h 14min', '2h 36min', '2h 0min', '1h 46min', '2h 3min', '2h 33min', '2h 52min', '2h 38min', '2h 55min', '2h 59min', '1h 29min', '1h 54min', '2h 22min', '2h 34min', '2h 8min', '1h 39min', '2h 12min', '1h 56min', '1h 50min', '1h 32min', '1h 34min', '2h 19min', '2h 36min', '2h 35min', '2h 36min', '2h 39min', '3h 21min', '2h 56min', '1h 35min', '2h 0min', '2h 7min', '2h 10min', '1h 57min', '2h 5min', '1h 30min', '1h 34min', '2h 38min', '2h 6min', '2h 1min', '2h 46min', '1h 50min', '1h 55min', '2h 46min', '2h 32min', '2h 38min', '1h 39min', '2h 18min', '2h 7min', '2h 21min', '2h 7min', '2h 12min', '2h 19min', '2h 20min', '1h 37min', '1h 50min', '1h 46min', '2h 39min', '1h 33min', '2h 36min', '1h 25min']
The number of runtime : 100

## **Scrapping Age Rating**

In [ ]:
# Write Your Code here
movie_age_rating = []
for url in movie_url:
  content = requests.get(url,headers = headers)
  soup = BeautifulSoup(content.text,'html.parser')
  age_rating = 'NA'
  for i in soup.find_all('div', class_ = 'detail-infos'):
    if i.find_all('h3')[0].text == 'Age rating' :
      age_rating = i.find_all('div')[0].text
      break
  movie_age_rating.append(age_rating)
print(movie_age_rating)
print('The number of rating is :', len(movie_age_rating))

['UA', 'UA', 'A', 'NA', 'U', 'UA', 'UA', 'NA', 'NA', 'UA', 'NA', 'A', 'UA', 'U', 'NA', 'NA', 'UA', 'A', 'NA', 'UA', 'UA', 'UA', 'UA', 'A', 'UA', 'A', 'A', 'U', 'NA', 'A', 'A', 'NA', 'UA', 'U', 'UA', 'UA', 'UA', 'NA', 'A', 'NA', 'U', 'UA', 'UA', 'U', 'UA', 'UA', 'UA', 'NA', 'A', 'UA', 'NA', 'NA', 'UA', 'UA', 'UA', 'A', 'NA', 'UA', 'NA', 'A', 'U', 'UA', 'U', 'NA', 'UA', 'U', 'A', 'A', 'NA', 'A', 'NA', 'UA', 'NA', 'NA', 'NA', 'NA', 'NA', 'UA', 'UA', 'UA', 'NA', 'A', 'UA', 'U', 'UA', 'NA', 'A', 'NA', 'NA', 'UA', 'A', 'UA', 'UA', 'U', 'UA', 'NA', 'UA', 'NA', 'UA', 'NA']
The number of rating is : 100

## **Fetching Production Countries Details**

In [ ]:
# Write Your Code here
movie_production_country = []
for url in movie_url:
  try:
    content = requests.get(url,headers = headers)
    soup = BeautifulSoup(content.text,'html.parser')
    for i in soup.find_all('div' , class_ = 'detail-infos'):
      if i.find_all('h3')[0].text == ' Production country ':
        country = i.find_all('div')[0].text
  except:
    country = 'NA'
  movie_production_country.append(country)
print(movie_production_country)
print('The number of movie production country is:' , len(movie_production_country))

['India', 'India', 'United States', 'France, United Kingdom', 'India', 'India', 'India', 'United States', 'India', 'India', 'Japan, United States', 'India', 'India', 'India', 'United Kingdom, United States', 'India', 'India', 'United States, Australia', 'India', 'India', 'India', 'United States, China', 'India', 'United States', 'India', 'India', 'United States, Canada', 'United States', 'United States', 'India, Sweden', 'India, United Kingdom', 'India', 'India', 'India', 'India', 'India', 'India', 'United States', 'United States', 'India', 'India', 'India', 'India', 'India', 'India', 'India', 'India', 'India', 'India', 'India', 'Canada, United States, United Kingdom', 'Poland', 'India', 'India', 'India', 'United States', 'India', 'India', 'United States', 'United States', 'United States', 'India', 'India', 'India', 'India', 'India', 'India', 'India', 'United States', 'South Korea', 'United States', 'India', 'Spain', 'United States', 'United States', 'France', 'India', 'Australia, Canada, United States', 'India', 'India', 'South Korea', 'United States', 'United States', 'United Kingdom, United States', 'India', 'United States, United Kingdom, Canada', 'Canada, United States', 'India', 'India', 'India', 'United States, Italy', 'India', 'India', 'United States', 'India', 'United States', 'India', 'United States', 'India', 'Japan']
The number of movie production country is: 100

## **Fetching Streaming Service Details**

In [ ]:
# Write Your Code here
movie_stream_service=[]
for url in movie_url:
  try:
     content=requests.get(url,headers=headers)
     soup=BeautifulSoup(content.text,'html.parser')
     names = [i['alt'] for i in soup.find_all('img', class_ = 'offer__icon')]
  except:
    names = 'NA'
  movie_stream_service.append(','.join(names))
print(movie_stream_service)

['Bookmyshow', 'Amazon Prime Video,Amazon Prime Video,Amazon Video', 'Apple TV,Hotstar,Apple TV', 'MUBI,MUBI Amazon Channel', 'Netflix', 'Bookmyshow', 'Amazon Prime Video,Amazon Prime Video,Amazon Video,Bookmyshow', 'Bookmyshow', 'Netflix', 'Hotstar', 'Bookmyshow', 'aha', 'Bookmyshow', 'Hotstar,Bookmyshow', 'Amazon Prime Video,Apple TV,Amazon Prime Video,Zee5,Amazon Video,Apple TV,Hungama Play,Apple TV', 'Amazon Prime Video,Amazon Prime Video', 'Amazon Prime Video,Amazon Prime Video,Amazon Video', 'Apple TV,Jio Cinema,Apple TV,Amazon Video,Apple TV', 'Bookmyshow', 'Amazon Prime Video,Amazon Prime Video,aha', 'Netflix', 'Amazon Prime Video,Apple TV,Amazon Prime Video,Sony Liv,VI movies and tv,Netflix,Jio Cinema,Zee5,Amazon Video,Apple TV,Apple TV', 'Netflix,Bookmyshow', 'Apple TV,Hotstar,Apple TV', 'Hotstar,Bookmyshow', 'Hotstar', 'Amazon Prime Video,Apple TV,Amazon Prime Video,Apple TV,Apple TV', 'Apple TV,Amazon Video,Apple TV,Apple TV', 'Amazon Prime Video,Amazon Prime Video', '', 'Netflix', 'Amazon Prime Video,Amazon Prime Video,Amazon Video', 'Bookmyshow', 'Hotstar', 'Amazon Prime Video,Amazon Prime Video,Netflix,Amazon Video', 'Bookmyshow', 'Netflix', 'Apple TV,Netflix,Zee5,Amazon Video,Apple TV,Apple TV', 'Apple TV,Netflix,Zee5,Amazon Video,Apple TV,Apple TV', 'Zee5', 'Hotstar', '', 'Amazon Prime Video,Amazon Prime Video', 'Amazon Prime Video,Amazon Prime Video', 'Hotstar', 'Amazon Prime Video,Amazon Prime Video,aha,Bookmyshow', 'Netflix', 'VI movies and tv,Netflix,Hotstar', 'VI movies and tv,Hotstar,Netflix,Bookmyshow', 'Amazon Prime Video,Amazon Prime Video,Amazon Video,Bookmyshow', 'Amazon Prime Video,Amazon Prime Video', 'Netflix', 'Amazon Prime Video,Amazon Prime Video,Amazon Video', 'Bookmyshow', 'Amazon Prime Video,Apple TV,Amazon Prime Video,VI movies and tv,Hotstar,Amazon Video,Apple TV,Apple TV', 'Apple TV,Jio Cinema,Apple TV', 'Chaupal Amazon Channel', 'Amazon Prime Video,Amazon Prime Video,ManoramaMax,aha', 'Apple TV,Zee5,Amazon Video,Apple TV,Apple TV', 'Netflix', 'Apple TV,Jio Cinema,Amazon Video,Zee5,Apple TV,Apple TV,Bookmyshow', 'VI movies and tv', 'Hotstar,aha,VI movies and tv', '', 'Hotstar', 'Sony Liv,Sun Nxt,ManoramaMax,aha,VI movies and tv,ManoramaMAX Amazon Channel,MX Player,Amazon miniTV', 'Netflix', 'Apple TV,aha,Apple TV,Apple TV', 'Lionsgate Play', 'Amazon Prime Video,Amazon Prime Video', 'Bookmyshow', 'Amazon Prime Video,Amazon Prime Video', 'Amazon Prime Video,Amazon Prime Video', 'Jio Cinema,Zee5', 'Netflix', 'Netflix', 'Amazon Prime Video,Amazon Prime Video,Hotstar,Amazon Video', 'Apple TV,Jio Cinema,Zee5,Amazon Video,Apple TV,Apple TV', 'Amazon Prime Video,Amazon Prime Video', 'Amazon Prime Video,Amazon Prime Video,VI movies and tv,Amazon Video', '', 'Apple TV,Amazon Video,Apple TV,Apple TV', 'Apple TV,Jio Cinema,Apple TV,Amazon Video,Apple TV', 'Apple TV,Jio Cinema,Tata Play,Apple TV,Apple TV,Bookmyshow', 'Netflix', 'Amazon Prime Video,Apple TV,Amazon Prime Video,Amazon Video,Apple TV,Apple TV', 'Apple TV,Apple TV,Amazon Video,Apple TV', 'Amazon Prime Video,Amazon Prime Video,Zee5', 'Netflix', 'Bookmyshow', 'Amazon Prime Video,Apple TV,Amazon Prime Video,Apple TV,Amazon Video,Apple TV', 'Sony Liv,VI movies and tv', 'Amazon Prime Video,Amazon Prime Video,Amazon Video', 'Apple TV,Hotstar,Apple TV,Amazon Video,Apple TV', 'Amazon Prime Video,Amazon Prime Video,aha', '', 'Zee5,VI movies and tv,Hotstar,Jio Cinema', 'Amazon Prime Video,Apple TV,Amazon Prime Video,Apple TV,Amazon Video,Apple TV', 'Amazon Prime Video,Amazon Prime Video,Jio Cinema,Amazon Video', '']

## **Now Creating Movies DataFrame**

In [ ]:
# Write Your Code here

info = {'Movie_URL' : movie_url, 'Movie_Name' : movie_title, 'Release_Year' : movie_year, 'Genres' : movie_genres, 'Runtime' : movie_runtime,
        'Age_Rating' : movie_age_rating, 'Production_Country' : movie_production_country, 'Rating' : imdb_rating , 'Stream_Service' : movie_stream_service }
data_movie = pd.DataFrame(info)
data_movie

,Movie_URL,Movie_Name,Release_Year,Genres,Runtime,Age_Rating,Production_Country,Rating,Stream_Service
0,https://www.justwatch.com/in/movie/bhool-bhula...,Bhool Bhulaiyaa 3 (2024),2024,"Comedy, Horror",2h 38min,UA,India,8.4,Bookmyshow
1,https://www.justwatch.com/in/movie/stree-2,Stree 2: Sarkate Ka Aatank (2024),2024,"Comedy, Horror",2h 27min,UA,India,7.0,"Amazon Prime Video,Amazon Prime Video,Amazon V..."
2,https://www.justwatch.com/in/movie/deadpool-3,Deadpool & Wolverine (2024),2024,"Comedy, Science-Fiction, Action & Adventure",2h 8min,A,United States,7.7,"Apple TV,Hotstar,Apple TV"
3,https://www.justwatch.com/in/movie/the-substance,The Substance (2024),2024,"Horror, Science-Fiction, Drama",2h 21min,NA,"France, United Kingdom",7.5,"MUBI,MUBI Amazon Channel"
4,https://www.justwatch.com/in/movie/meiyazhagan,Meiyazhagan (2024),2024,"Kids & Family, Drama",2h 57min,U,India,8.4,Netflix
...,...,...,...,...,...,...,...,...,...
95,https://www.justwatch.com/in/movie/subservience,Subservience (2024),2024,"Science-Fiction, Mystery & Thriller, Horror",1h 46min,NA,United States,8.3,
96,https://www.justwatch.com/in/movie/hanu-man,Hanu-Man (2024),2024,"Fantasy, Action & Adventure, Comedy, Science-F...",2h 39min,UA,India,7.8,"Zee5,VI movies and tv,Hotstar,Jio Cinema"
97,https://www.justwatch.com/in/movie/millers-girl,Miller's Girl (2024),2024,"Mystery & Thriller, Comedy, Drama",1h 33min,NA,United States,5.2,"Amazon Prime Video,Apple TV,Amazon Prime Video..."
98,https://www.justwatch.com/in/movie/double-ismart,Double Ismart (2024),2024,"Action & Adventure, Science-Fiction, Mystery &...",2h 36min,UA,India,2.9,"Amazon Prime Video,Amazon Prime Video,Jio Cine..."
99,https://www.justwatch.com/in/movie/haikyu-the-...,HAIKYU!! The Dumpster Battle (2024),2024,"Drama, Sport, Animation, Comedy",1h 25min,NA,Japan,2.9,

## **Scraping TV  Show Data**

In [ ]:
url ='https://www.justwatch.com/in/tv-shows?release_year_from=2000'
content = requests.get(url,headers=headers)
soup = BeautifulSoup(content.text,'html.parser')
soup

<!DOCTYPE html>
<html data-vue-meta="%7B%22dir%22:%7B%22ssr%22:%22ltr%22%7D,%22lang%22:%7B%22ssr%22:%22en%22%7D%7D" data-vue-meta-server-rendered="" dir="ltr" lang="en"><head><meta charset="utf-8"/><meta content="IE=edge" http-equiv="X-UA-Compatible"/><meta charset="utf-8" data-vue-meta="ssr"/><meta content="IE=edge" data-vue-meta="ssr" httpequiv="X-UA-Compatible"/><meta content="viewport-fit=cover, width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" data-vue-meta="ssr" name="viewport"/><meta content="JustWatch" data-vue-meta="ssr" property="og:site_name"/><meta content="794243977319785" data-vue-meta="ssr" property="fb:app_id"/><meta content="/appassets/img/JustWatch_logo_with_claim.png" data-vmid="og:image" data-vue-meta="ssr" property="og:image"/><meta content="606" data-vmid="og:image:width" data-vue-meta="ssr" property="og:image:width"/><meta content="302" data-vmid="og:image:height" data-vue-meta="ssr" property="og:image:height"/><meta content="yes" data-vue-meta="ssr" name="mobile-web-app-capable"/><meta content="yes" data-vue-meta="ssr" name="apple-mobile-web-app-capable"/><meta content="#182531" data-vue-meta="ssr" name="theme-color"/><meta content="AkO0-dINGfhSod2X6LeYIp9hwZc8ShczjzJA2a47dME" data-vue-meta="ssr" name="google-site-verification"/><meta content="d61y4roe8t5xwbb0gfu6gwe8j8iq3i" data-vue-meta="ssr" name="facebook-domain-verification"/><meta content="dmorpwc4h544ct6mv" data-vue-meta="ssr" name="dailymotion-domain-verification"/><meta content="dmm2vwzsugkzg13q5" data-vue-meta="ssr" name="dailymotion-domain-verification"/><meta content="Watch series online" data-vmid="og:title" data-vue-meta="ssr" property="og:title"/><meta content="watch series, watch tv series online, series online, online watch tv shows online, best shows to binge watch, popular tv shows" data-vue-meta="ssr" name="keywords"/><meta content="Where to watch TV series online? Find with JustWatch all the series you can stream online on Netflix, Hooq, Voot and 10 other streaming providers. Purchase, rent online &amp; flat-rate." data-vmid="description" data-vue-meta="ssr" name="description"/><meta content="Where to watch TV series online? Find with JustWatch all the series you can stream online on Netflix, Hooq, Voot and 10 other streaming providers. Purchase, rent online &amp; flat-rate." data-vmid="og:description" data-vue-meta="ssr" property="og:description"/><meta content="https://www.justwatch.com/in/tv-shows" data-vmid="og:url" data-vue-meta="ssr" property="og:url"/><meta content="noindex, follow" data-vmid="robots" data-vue-meta="ssr" name="robots"/><title>Watch series online</title><link as="font" crossorigin="true" data-vue-meta="ssr" href="/appassets/fonts/lato-regular.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="true" data-vue-meta="ssr" href="/appassets/fonts/lato-700.woff2" rel="preload" type="font/woff2"/><link as="font" crossorigin="true" data-vue-meta="ssr" href="/appassets/fonts/lato-900.woff2" rel="preload" type="font/woff2"/><link data-vue-meta="ssr" href="/appassets/favicon.ico" rel="icon"/><link data-vue-meta="ssr" href="https://www.googletagmanager.com/" rel="dns-prefetch"/><link data-vue-meta="ssr" href="https://ib.adnxs.com" rel="dns-prefetch"/><link data-vmid="canonical" data-vue-meta="ssr" href="https://www.justwatch.com/in/tv-shows" rel="canonical"/><link data-vue-meta="ssr" href="https://www.justwatch.com/ar/series" hreflang="es-AR" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/at/Serien" hreflang="de-AT" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/au/tv-shows" hreflang="en-AU" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/be/series" hreflang="fr-BE" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/bg/сериали" hreflang="bg-BG" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/br/series" hreflang="pt-BR" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/ca/tv-shows" hreflang="en-CA" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/ch/Serien" hreflang="de-CH" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/cl/series" hreflang="es-CL" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/co/series" hreflang="es-CO" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/cz/serialy" hreflang="cs-CZ" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/de/Serien" hreflang="de-DE" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/dk/tv-series" hreflang="en-DK" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/ec/series" hreflang="es-EC" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/eg/tv-shows" hreflang="ar-EG" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/es/series" hreflang="es-ES" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/fi/sarjat" hreflang="fi-FI" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/fr/series" hreflang="fr-FR" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/uk/tv-series" hreflang="en-GB" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/gr/τηλεοπτικές-σειρές" hreflang="el-GR" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/hk/電視節目" hreflang="zh-HK" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/hr/serije" hreflang="hr-HR" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/hu/tv-sorozat" hreflang="hu-HU" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/ie/tv-series" hreflang="en-IE" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/in/tv-shows" hreflang="en-IN" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/iq/tv-shows" hreflang="ar-IQ" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/is/þættir" hreflang="is-IS" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/it/serie-tv" hreflang="it-IT" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/jp/テレビ番組" hreflang="ja-JP" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/kr/TV-프로그램" hreflang="ko-KR" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/lb/tv-shows" hreflang="ar-LB" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/mx/series" hreflang="es-MX" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/my/tv-shows" hreflang="en-MY" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/nl/tv-series" hreflang="en-NL" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/no/tv-series" hreflang="en-NO" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/nz/tv-shows" hreflang="en-NZ" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/pe/series" hreflang="es-PE" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/ph/tv-shows" hreflang="en-PH" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/pl/seriale" hreflang="pl-PL" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/ps/tv-shows" hreflang="ar-PS" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/pt/series" hreflang="pt-PT" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/ro/seriale" hreflang="ro-RO" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/ru/сериалы" hreflang="ru-RU" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/se/tv-serier" hreflang="sv-SE" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/sg/tv-shows" hreflang="en-SG" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/sk/seriály" hreflang="sk-SK" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/tr/tv-dizileri" hreflang="tr-TR" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/us/tv-shows" hreflang="en-US" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/va/serie-tv" hreflang="it-VA" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/xk/seriale-televizive" hreflang="sq-XK" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/za/tv-series" hreflang="en-ZA" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/ee/seriaalid" hreflang="et-EE" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/lt/tv-laidos" hreflang="lt-LT" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/id/tv-shows" hreflang="en-ID" rel="alternate"/><link data-vue-meta="ssr" href="https://www.justwatch.com/tw/電視節目" hreflang="zh-TW" rel="alternate"/><base href="/" target="_self"/><link as="image" href="/appassets/img/logo/JustWatch-logo-large.webp" imagesrcset="/appassets/img/logo/JustWatch-logo-large.webp 1px" importance="high" rel="preload"/><link as="image" href="https://www.justwatch.com/images/icon/207360008/s100/netflix.{format}/icon.webp" imagesrcset="https://www.justwatch.com/images/icon/207360008/s100/netflix.{format}/icon.webp 1px" importance="high" media="(min-width: 0px)" rel="preload"/><link as="image" href="https://www.justwatch.com/images/icon/52449861/s100/amazonprimevideo.{format}/icon.webp" imagesrcset="https://www.justwatch.com/images/icon/52449861/s100/amazonprimevideo.{format}/icon.webp 1px" importance="high" media="(min-width: 0px)" rel="preload"/><link as="image" href="https://www.justwatch.com/images/icon/152862153/s100/appletvplus.{format}/icon.webp" imagesrcset="https://www.justwatch.com/images/icon/152862153/s100/appletvplus.{format}/icon.webp 1px" importance="high" media="(min-width: 0px)" rel="preload"/><link as="image" href="https://www.justwatch.com/images/icon/190848813/s100/itunes.{format}/icon.webp" imagesrcset="https://www.justwatch.com/images/icon/190848813/s100/itunes.{format}/icon.webp 1px" importance="high" media="(min-width: 0px)" rel="preload"/><link as="image" href="https://www.justwatch.com/images/icon/127445869/s100/crunchyroll.{format}/icon.webp" imagesrcset="https://www.justwatch.com/images/icon/127445869/s100/crunchyroll.{format}/icon.webp 1px" importance="high" media="(min-width: 0px)" rel="preload"/><link as="image" href="https://www.justwatch.com/images/icon/240029443/s100/hotstar.{format}/icon.webp" imagesrcset="https://www.justwatch.com/images/icon/240029443/s100/hotstar.{format}/icon.webp 1px" importance="high" media="(min-width: 0px)" rel="preload"/><link as="image" href="https://www.justwatch.com/images/icon/312325227/s100/jiocinema.{format}/icon.webp" imagesrcset="https://www.justwatch.com/images/icon/312325227/s100/jiocinema.{format}/icon.webp 1px" importance="high" media="(min-width: 0px)" rel="preload"/><link as="image" href="https://www.justwatch.com/images/poster/321587622/s332/from.webp" imagesrcset="https://www.justwatch.com/images/poster/321587622/s332/from.webp 1px, https://www.justwatch.com/images/poster/321587622/s332/from.webp" importance="high" rel="preload"/><link as="image" href="https://www.justwatch.com/images/poster/320834237/s332/the-penguin.webp" imagesrcset="https://www.justwatch.com/images/poster/320834237/s332/the-penguin.webp 1px, https://www.justwatch.com/images/poster/320834237/s332/the-penguin.webp" importance="high" rel="preload"/><link as="image" href="https://www.justwatch.com/images/poster/321929402/s332/citadel-honey-bunny.webp" imagesrcset="https://www.justwatch.com/images/poster/321929402/s332/citadel-honey-bunny.webp 1px, https://www.justwatch.com/images/poster/321929402/s332/citadel-honey-bunny.webp" importance="high" rel="preload"/><link as="image" href="https://www.justwatch.com/images/poster/302379741/s332/taaza-khabar.webp" imagesrcset="https://www.justwatch.com/images/poster/302379741/s332/taaza-khabar.webp 1px, https://www.justwatch.com/images/poster/302379741/s332/taaza-khabar.webp" importance="high" rel="preload"/><style data-vue-ssr-id="16dee5de:0 16dee5de:1 374c0f88:0 61943ce6:0 c9008484:0 a55614a4:0 2922e121:0 275e282f:0 5fbc3e0a:0 6477115b:0 016f7854:0 2f594a84:0 07f6a070:0 1c1c7876:0 722b1bb4:0 89c5701e:0 2935cc78:0 18cad8ea:0 61d60340:0 93d5461c:0 3bdce1a2:0 0cd1495d:0 9df6854c:0 1d549892:0 772a1a34:0 75a9bc05:0 67f80acd:0 7a6fba76:0 692f787c:0 64954408:0 4c8f0d7c:0 1ccfd6a3:0 bdcde3be:0 90f1276c:0 6ba62192:0">html.ios{--ion-default-font:-apple-system,BlinkMacSystemFont,"Helvetica Neue","Roboto",sans-serif}html.md{--ion-default-font:"Roboto","Helvetica Neue",sans-serif}html{--ion-font-family:var(--ion-default-font)}body{background:var(--ion-background-color)}body.backdrop-no-scroll{overflow:hidden}html.ios ion-modal.modal-card .ion-page>ion-header>ion-toolbar:first-of-type{padding-top:0}html.ios ion-modal .ion-page{border-radius:inherit}.ion-color-primary{--ion-color-base:var(--ion-color-primary,#3880ff)!important;--ion-color-base-rgb:var(--ion-color-primary-rgb,56,128,255)!important;--ion-color-contrast:var(--ion-color-primary-contrast,#fff)!important;--ion-color-contrast-rgb:var(--ion-color-primary-contrast-rgb,255,255,255)!important;--ion-color-shade:var(--ion-color-primary-shade,#3171e0)!important;--ion-color-tint:var(--ion-color-primary-tint,#4c8dff)!important}.ion-color-secondary{--ion-color-base:var(--ion-color-secondary,#3dc2ff)!important;--ion-color-base-rgb:var(--ion-color-secondary-rgb,61,194,255)!important;--ion-color-contrast:var(--ion-color-secondary-contrast,#fff)!important;--ion-color-contrast-rgb:var(--ion-color-secondary-contrast-rgb,255,255,255)!important;--ion-color-shade:var(--ion-color-secondary-shade,#36abe0)!important;--ion-color-tint:var(--ion-color-secondary-tint,#50c8ff)!important}.ion-color-tertiary{--ion-color-base:var(--ion-color-tertiary,#5260ff)!important;--ion-color-base-rgb:var(--ion-color-tertiary-rgb,82,96,255)!important;--ion-color-contrast:var(--ion-color-tertiary-contrast,#fff)!important;--ion-color-contrast-rgb:var(--ion-color-tertiary-contrast-rgb,255,255,255)!important;--ion-color-shade:var(--ion-color-tertiary-shade,#4854e0)!important;--ion-color-tint:var(--ion-color-tertiary-tint,#6370ff)!important}.ion-color-success{--ion-color-base:var(--ion-color-success,#2dd36f)!important;--ion-color-base-rgb:var(--ion-color-success-rgb,45,211,111)!important;--ion-color-contrast:var(--ion-color-success-contrast,#fff)!important;--ion-color-contrast-rgb:var(--ion-color-success-contrast-rgb,255,255,255)!important;--ion-color-shade:var(--ion-color-success-shade,#28ba62)!important;--ion-color-tint:var(--ion-color-success-tint,#42d77d)!important}.ion-color-warning{--ion-color-base:var(--ion-color-warning,#ffc409)!important;--ion-color-base-rgb:var(--ion-color-warning-rgb,255,196,9)!important;--ion-color-contrast:var(--ion-color-warning-contrast,#000)!important;--ion-color-contrast-rgb:var(--ion-color-warning-contrast-rgb,0,0,0)!important;--ion-color-shade:var(--ion-color-warning-shade,#e0ac08)!important;--ion-color-tint:var(--ion-color-warning-tint,#ffca22)!important}.ion-color-danger{--ion-color-base:var(--ion-color-danger,#eb445a)!important;--ion-color-base-rgb:var(--ion-color-danger-rgb,235,68,90)!important;--ion-color-contrast:var(--ion-color-danger-contrast,#fff)!important;--ion-color-contrast-rgb:var(--ion-color-danger-contrast-rgb,255,255,255)!important;--ion-color-shade:var(--ion-color-danger-shade,#cf3c4f)!important;--ion-color-tint:var(--ion-color-danger-tint,#ed576b)!important}.ion-color-light{--ion-color-base:var(--ion-color-light,#f4f5f8)!important;--ion-color-base-rgb:var(--ion-color-light-rgb,244,245,248)!important;--ion-color-contrast:var(--ion-color-light-contrast,#000)!important;--ion-color-contrast-rgb:var(--ion-color-light-contrast-rgb,0,0,0)!important;--ion-color-shade:var(--ion-color-light-shade,#d7d8da)!important;--ion-color-tint:var(--ion-color-light-tint,#f5f6f9)!important}.ion-color-medium{--ion-color-base:var(--ion-color-medium,#92949c)!important;--ion-color-base-rgb:var(--ion-color-medium-rgb,146,148,156)!important;--ion-color-contrast:var(--ion-color-medium-contrast,#fff)!important;--ion-color-contrast-rgb:var(--ion-color-medium-contrast-rgb,255,255,255)!important;--ion-color-shade:var(--ion-color-medium-shade,#808289)!important;--ion-color-tint:var(--ion-color-medium-tint,#9d9fa6)!important}.ion-color-dark{--ion-color-base:var(--ion-color-dark,#222428)!important;--ion-color-base-rgb:var(--ion-color-dark-rgb,34,36,40)!important;--ion-color-contrast:var(--ion-color-dark-contrast,#fff)!important;--ion-color-contrast-rgb:var(--ion-color-dark-contrast-rgb,255,255,255)!important;--ion-color-shade:var(--ion-color-dark-shade,#1e2023)!important;--ion-color-tint:var(--ion-color-dark-tint,#383a3e)!important}.ion-page{left:0;right:0;top:0;bottom:0;display:flex;position:absolute;flex-direction:column;justify-content:space-between;contain:layout size style;overflow:hidden;z-index:0}.split-pane-visible>.ion-page.split-pane-main{position:relative}.ion-page-hidden,[hidden],ion-action-sheet-controller,ion-alert-controller,ion-loading-controller,ion-menu-controller,ion-modal-controller,ion-nav-controller,ion-picker-controller,ion-popover-controller,ion-route,ion-route-redirect,ion-router,ion-select-option,ion-toast-controller{display:none!important}.ion-page-invisible{opacity:0}.can-go-back>ion-header ion-back-button{display:block}html.plt-ios.plt-hybrid,html.plt-ios.plt-pwa{--ion-statusbar-padding:20px}@supports(padding-top:20px){html{--ion-safe-area-top:var(--ion-statusbar-padding)}}@supports(padding-top:constant(safe-area-inset-top)){html{--ion-safe-area-top:constant(safe-area-inset-top);--ion-safe-area-bottom:constant(safe-area-inset-bottom);--ion-safe-area-left:constant(safe-area-inset-left);--ion-safe-area-right:constant(safe-area-inset-right)}}@supports(padding-top:env(safe-area-inset-top)){html{--ion-safe-area-top:env(safe-area-inset-top);--ion-safe-area-bottom:env(safe-area-inset-bottom);--ion-safe-area-left:env(safe-area-inset-left);--ion-safe-area-right:env(safe-area-inset-right)}}ion-card-header.ion-color .ion-inherit-color,ion-card.ion-color .ion-inherit-color{color:inherit}.menu-content{transform:translateZ(0)}.menu-content-open{cursor:pointer;touch-action:manipulation;pointer-events:none}.ios .menu-content-reveal{box-shadow:-8px 0 42px rgba(0,0,0,.08)}[dir=rtl].ios .menu-content-reveal{box-shadow:8px 0 42px rgba(0,0,0,.08)}.md .menu-content-push,.md .menu-content-reveal{box-shadow:4px 0 16px rgba(0,0,0,.18)}
/*!
 * Bootstrap v3.3.7 (http://getbootstrap.com)
 * Copyright 2011-2016 Twitter, Inc.
 * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)

## **Fetching Tv shows Url details**

In [ ]:
# Write Your Code here
tv_url = []
for i in soup.find_all('a' , class_ = 'title-list-grid__item--link'):
  tv_url.append('https://www.justwatch.com'+ i['href'])
print(tv_url)
print('Total TV show is :', len(tv_url))

['https://www.justwatch.com/in/tv-show/from', 'https://www.justwatch.com/in/tv-show/the-penguin', 'https://www.justwatch.com/in/tv-show/citadel-honey-bunny', 'https://www.justwatch.com/in/tv-show/taaza-khabar', 'https://www.justwatch.com/in/tv-show/mirzapur', 'https://www.justwatch.com/in/tv-show/the-day-of-the-jackal', 'https://www.justwatch.com/in/tv-show/x-x-x-uncensored', 'https://www.justwatch.com/in/tv-show/dont-come-home', 'https://www.justwatch.com/in/tv-show/bigg-boss', 'https://www.justwatch.com/in/tv-show/agatha-house-of-harkness', 'https://www.justwatch.com/in/tv-show/hellbound', 'https://www.justwatch.com/in/tv-show/the-diplomat', 'https://www.justwatch.com/in/tv-show/game-of-thrones', 'https://www.justwatch.com/in/tv-show/sweetpea', 'https://www.justwatch.com/in/tv-show/tulsa-king', 'https://www.justwatch.com/in/tv-show/1000-babies', 'https://www.justwatch.com/in/tv-show/mastram', 'https://www.justwatch.com/in/tv-show/the-legend-of-hanuman', 'https://www.justwatch.com/in/tv-show/arcane', 'https://www.justwatch.com/in/tv-show/yellowstone', 'https://www.justwatch.com/in/tv-show/the-pradeeps-of-pittsburgh', 'https://www.justwatch.com/in/tv-show/panchayat', 'https://www.justwatch.com/in/tv-show/the-rookie', 'https://www.justwatch.com/in/tv-show/dan-da-dan', 'https://www.justwatch.com/in/tv-show/nobody-wants-this', 'https://www.justwatch.com/in/tv-show/teacup', 'https://www.justwatch.com/in/tv-show/dune-the-sisterhood', 'https://www.justwatch.com/in/tv-show/breaking-bad', 'https://www.justwatch.com/in/tv-show/murder-mindfully', 'https://www.justwatch.com/in/tv-show/gandii-baat', 'https://www.justwatch.com/in/tv-show/only-murders-in-the-building', 'https://www.justwatch.com/in/tv-show/untitled-kapil-sharma-netflix-project', 'https://www.justwatch.com/in/tv-show/say-nothing', 'https://www.justwatch.com/in/tv-show/georgie-and-mandys-first-marriage', 'https://www.justwatch.com/in/tv-show/person-of-interest', 'https://www.justwatch.com/in/tv-show/house-of-the-dragon', 'https://www.justwatch.com/in/tv-show/mithya', 'https://www.justwatch.com/in/tv-show/kill-me-love-me', 'https://www.justwatch.com/in/tv-show/the-judge-from-hell', 'https://www.justwatch.com/in/tv-show/special-ops-lioness', 'https://www.justwatch.com/in/tv-show/silo', 'https://www.justwatch.com/in/tv-show/the-boys', 'https://www.justwatch.com/in/tv-show/apharan', 'https://www.justwatch.com/in/tv-show/shogun-2024', 'https://www.justwatch.com/in/tv-show/paperhouse', 'https://www.justwatch.com/in/tv-show/paris-has-fallen', 'https://www.justwatch.com/in/tv-show/dark', 'https://www.justwatch.com/in/tv-show/dragon-ball-daima', 'https://www.justwatch.com/in/tv-show/murder-in-mahim', 'https://www.justwatch.com/in/tv-show/farzi', 'https://www.justwatch.com/in/tv-show/high-potential', 'https://www.justwatch.com/in/tv-show/doubt-2024', 'https://www.justwatch.com/in/tv-show/superman-and-lois', 'https://www.justwatch.com/in/tv-show/spartacus', 'https://www.justwatch.com/in/tv-show/the-lord-of-the-rings-the-rings-of-power', 'https://www.justwatch.com/in/tv-show/the-lincoln-lawyer', 'https://www.justwatch.com/in/tv-show/cross', 'https://www.justwatch.com/in/tv-show/demon-slayer-kimetsu-no-yaiba', 'https://www.justwatch.com/in/tv-show/cobra-kai', 'https://www.justwatch.com/in/tv-show/jujutsu-kaisen', 'https://www.justwatch.com/in/tv-show/this-is-the-zodiac-speaking', 'https://www.justwatch.com/in/tv-show/scam-1992', 'https://www.justwatch.com/in/tv-show/attack-on-titan', 'https://www.justwatch.com/in/tv-show/disclaimer', 'https://www.justwatch.com/in/tv-show/auto-shankar', 'https://www.justwatch.com/in/tv-show/hidden-love', 'https://www.justwatch.com/in/tv-show/peaky-blinders', 'https://www.justwatch.com/in/tv-show/modern-family', 'https://www.justwatch.com/in/tv-show/naruto-shippuden', 'https://www.justwatch.com/in/tv-show/raising-voices', 'https://www.justwatch.com/in/tv-show/fresh-off-the-boat', 'https://www.justwatch.com/in/tv-show/aashram', 'https://www.justwatch.com/in/tv-show/gyaarah-gyaarah', 'https://www.justwatch.com/in/tv-show/adams-sweet-agony', 'https://www.justwatch.com/in/tv-show/ghosts-2021', 'https://www.justwatch.com/in/tv-show/deceitful-love', 'https://www.justwatch.com/in/tv-show/murshid', 'https://www.justwatch.com/in/tv-show/aindham-vedham', 'https://www.justwatch.com/in/tv-show/the-flash', 'https://www.justwatch.com/in/tv-show/the-devils-hour', 'https://www.justwatch.com/in/tv-show/young-sheldon', 'https://www.justwatch.com/in/tv-show/euphoria', 'https://www.justwatch.com/in/tv-show/white-collar', 'https://www.justwatch.com/in/tv-show/banshee', 'https://www.justwatch.com/in/tv-show/mandaar', 'https://www.justwatch.com/in/tv-show/the-big-bang-theory', 'https://www.justwatch.com/in/tv-show/true-detective', 'https://www.justwatch.com/in/tv-show/house', 'https://www.justwatch.com/in/tv-show/evil', 'https://www.justwatch.com/in/tv-show/territory', 'https://www.justwatch.com/in/tv-show/naruto', 'https://www.justwatch.com/in/tv-show/the-walking-dead-daryl-dixon', 'https://www.justwatch.com/in/tv-show/the-vampire-diaries', 'https://www.justwatch.com/in/tv-show/bleach-thousand-year-blood-war', 'https://www.justwatch.com/in/tv-show/stranger-things', 'https://www.justwatch.com/in/tv-show/vikings', 'https://www.justwatch.com/in/tv-show/fabulous-lives-of-bollywood-wives', 'https://www.justwatch.com/in/tv-show/we-were-kings', 'https://www.justwatch.com/in/tv-show/prison-break', 'https://www.justwatch.com/in/tv-show/suits']
Total TV show is : 100

## **Fetching Tv Show Title details**

In [ ]:
# Write Your Code here
tv_show_title = []
for url in tv_url:
  try:
    content = requests.get(url , headers = headers)
    soup = BeautifulSoup(content.text,'html.parser')
    title = soup.find_all('h1')[0].text
  except:
    title = 'NA'
  tv_show_title.append(title)
print(tv_show_title)
print('The Number of title', len(tv_show_title))

[' From (2022)', ' The Penguin (2024)', ' Citadel: Honey Bunny (2024)', ' Taaza Khabar (2023)', ' Mirzapur (2018)', ' The Day of the Jackal (2024)', ' XXX: Uncensored (2018)', " Don't Come Home (2024)", ' Bigg Boss (2006)', ' Agatha All Along (2024)', ' Hellbound (2021)', ' The Diplomat (2023)', ' Game of Thrones (2011)', ' Sweetpea (2024)', ' Tulsa King (2022)', ' 1000 Babies (2024)', ' Mastram (2020)', ' The Legend of Hanuman (2021)', ' Arcane (2021)', ' Yellowstone (2018)', ' The Pradeeps of Pittsburgh (2024)', ' Panchayat (2020)', ' The Rookie (2018)', ' Dan Da Dan (2024)', ' Nobody Wants This (2024)', ' Teacup (2024)', ' Dune: Prophecy (2024)', ' Breaking Bad (2008)', ' Murder Mindfully (2024)', ' Gandii Baat (2018)', ' Only Murders in the Building (2021)', ' The Great Indian Kapil Show (2024)', ' Say Nothing (2024)', " Georgie & Mandy's First Marriage (2024)", ' Person of Interest (2011)', ' House of the Dragon (2022)', ' Mithya (2022)', ' Kill Me Love Me (2024)', ' The Judge from Hell (2024)', ' Lioness (2023)', ' Silo (2023)', ' The Boys (2019)', ' Apharan (2018)', ' Shōgun (2024)', ' Money Heist (2017)', ' Paris Has Fallen (2024)', ' Dark (2017)', ' Dragon Ball DAIMA (2024)', ' Murder in Mahim (2024)', ' Farzi (2023)', ' High Potential (2024)', ' Doubt (2024)', ' Superman & Lois (2021)', ' Spartacus (2010)', ' The Lord of the Rings: The Rings of Power (2022)', ' The Lincoln Lawyer (2022)', ' Cross (2024)', ' Demon Slayer: Kimetsu no Yaiba (2019)', ' Cobra Kai (2018)', ' Jujutsu Kaisen (2020)', ' This Is the Zodiac Speaking (2024)', ' Scam 1992: The Harshad Mehta Story (2020)', ' Attack on Titan (2013)', ' Disclaimer (2024)', ' Auto Shankar (2019)', ' Hidden Love (2023)', ' Peaky Blinders (2013)', ' Modern Family (2009)', ' Naruto Shippūden (2007)', ' Raising Voices (2024)', ' Fresh Off the Boat (2015)', ' Aashram (2020)', ' Gyaarah Gyaarah (2024)', " Adam's Sweet Agony (2024)", ' Ghosts (2021)', ' Deceitful Love (2024)', ' Murshid (2024)', ' Aindham Vedham (2024)', ' The Flash (2014)', " The Devil's Hour (2022)", ' Young Sheldon (2017)', ' Euphoria (2019)', ' White Collar (2009)', ' Banshee (2013)', ' Mandaar (2021)', ' The Big Bang Theory (2007)', ' True Detective (2014)', ' House (2004)', ' Evil (2021)', ' Territory (2024)', ' Naruto (2002)', ' The Walking Dead: Daryl Dixon (2023)', ' The Vampire Diaries (2009)', ' Bleach: Thousand-Year Blood War (2022)', ' Stranger Things (2016)', ' Vikings (2013)', ' Fabulous Lives of Bollywood Wives (2020)', ' We Were Kings (2024)', ' Prison Break (2005)', ' Suits (2011)']
The Number of title 100

## **Fetching Release Year**

In [ ]:
# Write Your Code here
tv_year = []
for url in tv_url:
  try:
    content = requests.get(url,headers = headers)
    soup = BeautifulSoup(content.text, 'html.parser')
    year = soup.find_all('span' , class_= 'release-year')[0].text.strip('()')
  except:
    year = 'NA'
  tv_year.append(year)
print(tv_year)
print('Total number of movie:', len(tv_year))

['2022', '2024', '2024', '2023', '2018', '2024', '2018', '2024', '2006', '2024', '2021', '2023', '2011', '2024', '2022', '2024', '2020', '2021', '2021', '2018', '2024', '2020', '2018', '2024', '2024', '2024', '2024', '2008', '2024', '2018', '2021', '2024', '2024', '2024', '2011', '2022', '2022', '2024', '2024', '2023', '2023', '2019', '2018', '2024', '2017', '2024', '2017', '2024', '2024', '2023', '2024', '2024', '2021', '2010', '2022', '2022', '2024', '2019', '2018', '2020', '2024', '2020', '2013', '2024', '2019', '2023', '2013', '2009', '2007', '2024', '2015', '2020', '2024', '2024', '2021', '2024', '2024', '2024', '2014', '2022', '2017', '2019', '2009', '2013', '2021', '2007', '2014', '2004', '2021', '2024', '2002', '2023', '2009', '2022', '2016', '2013', '2020', '2024', '2005', '2011']
Total number of movie: 100

## **Fetching TV Show Genre Details**

In [ ]:
# Write Your Code here
tv_genres = []
for url in tv_url:
  try:
    content = requests.get(url,headers = headers)
    soup = BeautifulSoup(content.text,'html.parser')
    for i in soup.find_all('div', class_ = 'detail-infos'):
      if i.find_all('h3')[0].text == 'Genres':
        genres = i.find_all('span')[0].text
  except:
    genres = 'NA'
  tv_genres.append(genres)
print(tv_genres)
print(f'Total number of genres is : {len(tv_genres)}')

['Drama, Horror, Science-Fiction, Mystery & Thriller', 'Crime, Drama, Fantasy', 'Action & Adventure, Drama, Science-Fiction, Mystery & Thriller', 'Science-Fiction, Drama, Fantasy, Mystery & Thriller, Action & Adventure, Comedy', 'Action & Adventure, Drama, Mystery & Thriller, Crime', 'Crime, Drama, Mystery & Thriller, Action & Adventure', 'Comedy, Drama, Romance', 'Mystery & Thriller, Drama, Horror, Science-Fiction', 'Reality TV, Kids & Family', 'Science-Fiction, Mystery & Thriller, Comedy, Drama, Fantasy, Action & Adventure', 'Drama, Crime, Science-Fiction, Fantasy, Horror, Mystery & Thriller', 'Drama, War & Military, Mystery & Thriller', 'Science-Fiction, Drama, Action & Adventure, Fantasy', 'Comedy, Drama', 'Drama, Crime', 'Crime, Drama, Horror', 'Comedy, Drama, Fantasy', 'Kids & Family, Fantasy, Animation, Action & Adventure', 'Drama, Fantasy, Science-Fiction, Animation, Action & Adventure, Mystery & Thriller', 'Western, Drama', 'Comedy, Drama', 'Drama, Comedy', 'Crime, Drama, Comedy, Action & Adventure', 'Action & Adventure, Science-Fiction, Romance, Mystery & Thriller, Animation, Comedy, Fantasy', 'Comedy, Romance, Drama', 'Science-Fiction, Drama, Mystery & Thriller, Horror', 'Drama, Science-Fiction, Action & Adventure', 'Drama, Crime, Mystery & Thriller', 'Comedy, Crime, Mystery & Thriller', 'Drama, Mystery & Thriller, Crime', 'Drama, Mystery & Thriller, Comedy, Crime', 'Comedy', 'Drama, Crime, History, Mystery & Thriller', 'Comedy', 'Drama, Action & Adventure, Crime, Science-Fiction, Mystery & Thriller', 'Science-Fiction, Drama, Action & Adventure, Fantasy, Romance', 'Drama, Crime, Mystery & Thriller', 'Drama, Action & Adventure', 'Comedy, Drama, Science-Fiction, Crime, Romance, Fantasy, Horror', 'Drama, War & Military, Action & Adventure, Mystery & Thriller', 'Drama, Science-Fiction', 'Science-Fiction, Action & Adventure, Drama, Comedy, Crime', 'Mystery & Thriller, Action & Adventure, Crime, Drama', 'War & Military, History, Drama', 'Crime, Drama, Mystery & Thriller, Action & Adventure, Made in Europe', 'Action & Adventure, War & Military, Drama', 'Crime, Drama, Science-Fiction, Mystery & Thriller', 'Animation, Action & Adventure, Comedy, Science-Fiction, Fantasy', 'Crime', 'Drama, Crime, Mystery & Thriller', 'Crime, Drama', 'Crime, Mystery & Thriller, Drama', 'Drama, Science-Fiction, Action & Adventure', 'Drama, Romance, Action & Adventure', 'Action & Adventure, Science-Fiction, Drama, Fantasy', 'Mystery & Thriller, Crime, Drama', 'Mystery & Thriller, Action & Adventure, Crime, Drama', 'Animation, Action & Adventure, Science-Fiction, Fantasy, Mystery & Thriller', 'Action & Adventure, Drama, Comedy, Sport', 'Animation, Action & Adventure, Fantasy, Mystery & Thriller, Science-Fiction', 'Documentary, Crime', 'Drama, Mystery & Thriller, Crime', 'Fantasy, Horror, Animation, Action & Adventure, Drama, Science-Fiction', 'Drama, Mystery & Thriller', 'Crime, Mystery & Thriller', 'Drama', 'Drama, Crime', 'Comedy, Drama, Romance', 'Science-Fiction, Animation, Action & Adventure, Comedy, Drama, Fantasy', 'Drama', 'Comedy', 'Drama, Crime, Mystery & Thriller', 'Drama, Fantasy, Science-Fiction', 'Animation', 'Comedy, Fantasy', 'Drama, Romance', 'Crime, Mystery & Thriller', 'Mystery & Thriller', 'Science-Fiction, Drama, Action & Adventure', 'Mystery & Thriller, Crime, Drama', 'Comedy, Kids & Family, Drama', 'Drama', 'Mystery & Thriller, Drama, Comedy, Crime', 'Crime, Drama, Mystery & Thriller, Action & Adventure', 'Drama', 'Comedy, Romance', 'Drama, Mystery & Thriller, Crime', 'Mystery & Thriller, Comedy, Drama', 'Drama, Mystery & Thriller, Crime, Horror', 'Drama, Western, Action & Adventure', 'Action & Adventure, Science-Fiction, Fantasy, Animation, Comedy', 'Science-Fiction, Action & Adventure, Drama, Horror', 'Drama, Science-Fiction, Fantasy, Horror, Romance, Mystery & Thriller', 'Fantasy, Animation, Action & Adventure', 'Drama, Science-Fiction, Action & Adventure, Mystery & Thriller, Fantasy, Horror', 'War & Military, History, Romance, Action & Adventure, Drama, Made in Europe', 'Reality TV, Documentary, Romance', 'Drama, Crime', 'Action & Adventure, Crime, Drama, Mystery & Thriller, Made in Europe', 'Drama, Comedy']
Total number of genres is : 100

## **Fetching IMDB Rating Details**

In [ ]:
# Write Your Code here
imdb_rating = []
for url in tv_url:
  try:
    content = requests.get(url, headers = headers)
    soup = BeautifulSoup(content.text,'html.parser')
    for i in soup.find_all('div', class_ = 'detail-infos'):
      if i.find_all('h3')[0].text =='Rating':
        rating = i.find_all('div')[0].text.strip().split()[0]
  except:
    rating = 'NA'
  imdb_rating.append(rating)
print(imdb_rating)
print(f'Number of imdb_rating is : {len(imdb_rating)}')

['7.8', '8.8', '6.3', '8.1', '8.4', '8.1', '4.8', '7.3', '7.3', '7.3', '6.6', '8.0', '9.2', '7.2', '8.0', '7.2', '6.9', '9.1', '9.0', '8.7', '6.2', '9.0', '9.0', '8.7', '7.9', '6.4', '7.5', '9.5', '7.5', '3.4', '8.1', '6.8', '8.4', '8.4', '8.4', '8.3', '7.7', '7.4', '7.9', '7.9', '8.1', '8.7', '8.2', '8.6', '8.2', '6.6', '8.7', '8.1', '7.8', '8.3', '8.3', '8.3', '7.7', '8.5', '6.9', '7.8', '7.2', '8.6', '8.4', '8.5', '7.2', '9.2', '9.1', '7.5', '6.8', 'NA', '8.7', '8.5', '8.7', '7.2', '7.8', '7.8', '8.2', 'NA', '7.9', '5.6', '7.4', '7.5', '7.5', '7.6', '7.7', '8.3', '8.2', '8.4', 'NA', '8.1', '8.9', '8.7', '7.8', '6.9', '8.4', '7.5', '7.7', '9.0', '8.7', '8.5', '4.2', '5.1', '8.3', '8.4']
Number of imdb_rating is : 100

## **Fetching Age Rating Details**

In [ ]:
# Write Your Code here
tv_age_rating = []
for url in tv_url:
  content = requests.get(url,headers = headers)
  soup = BeautifulSoup(content.text,'html.parser')
  age_rating = 'NA'
  for i in soup.find_all('div', class_ = 'detail-infos'):
    if i.find_all('h3')[0].text == 'Age rating' :
      age_rating = i.find_all('div')[0].text
      break
  tv_age_rating.append(age_rating)
print(tv_age_rating)
print('The number of rating is :', len(tv_age_rating))

['NA', 'NA', 'NA', 'NA', 'A', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'A', 'U', 'NA', 'NA', 'A', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'A', 'A', 'A', 'NA', 'NA', 'NA', 'NA', 'U', 'A', 'NA', 'NA', 'NA', 'NA', 'A', 'A', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'NA', 'UA', 'A', 'UA', 'NA', 'A', 'NA', 'U', 'A', 'U', 'NA', 'A', 'NA', 'NA', 'A', 'A', 'NA', 'U', 'NA', 'NA', 'A', 'U', 'NA', 'NA', 'U', 'U', 'U', 'NA', 'NA', 'NA', 'NA', 'U', 'NA', 'NA', 'A', 'NA', 'A', 'U', 'NA']
The number of rating is : 100

## **Fetching Production Country details**

In [ ]:
# Write Your Code here
tv_production_country = []
for url in tv_url:
  try:
    content = requests.get(url,headers = headers)
    soup = BeautifulSoup(content.text,'html.parser')
    for i in soup.find_all('div' , class_ = 'detail-infos'):
      if i.find_all('h3')[0].text == ' Production country ':
        country = i.find_all('div')[0].text
  except:
    country = 'NA'
  tv_production_country.append(country)
print(tv_production_country)
print('The number of movie production country is:' , len(tv_production_country))

['United States', 'United States', 'India', 'India', 'India', 'United Kingdom', 'India', 'Thailand', 'India', 'United States', 'South Korea', 'United States', 'United States', 'United Kingdom', 'United States', 'India', 'India', 'India', 'United States, France', 'United States', 'United States, Canada', 'India', 'United States', 'Japan', 'United States', 'United States', 'United States', 'United States', 'Germany', 'India', 'United States', 'India', 'United States', 'United States', 'United States', 'United States', 'India', 'China', 'South Korea', 'United States', 'United States', 'United States', 'India', 'United States', 'Spain', 'France', 'Germany', 'Japan', 'India', 'India', 'United States', 'South Korea', 'United States', 'United States', 'United States', 'United States', 'United States', 'Japan', 'United States', 'Japan, United States', 'United States', 'India', 'Japan', 'United Kingdom', 'India', 'China', 'United Kingdom', 'United States', 'Japan', 'Spain', 'United States', 'India', 'India', 'Japan', 'United States', 'Italy', 'India', 'India', 'United States', 'United Kingdom', 'United States', 'United States', 'United States', 'United States', 'India', 'United States', 'United States', 'United States', 'United States', 'Australia', 'Japan', 'United States', 'United States', 'Japan', 'United States', 'Canada', 'India', 'Mexico', 'United States', 'United States']
The number of movie production country is: 100

## **Fetching Streaming Service details**

In [ ]:
# Write Your Code here
tv_stream_service=[]
for url in tv_url:
  try:
     content=requests.get(url,headers=headers)
     soup=BeautifulSoup(content.text,'html.parser')
     names = [i['alt'] for i in soup.find_all('img', class_ = 'offer__icon')]
  except:
    names = 'NA'
  tv_stream_service.append(','.join(names))
print(tv_stream_service)

['Amazon Prime Video,Amazon Prime Video', 'Jio Cinema', 'Amazon Prime Video,Amazon Prime Video', 'Hotstar', 'Amazon Prime Video,Amazon Prime Video', 'Jio Cinema', 'Alt Balaji', 'Netflix', 'Hotstar', 'Hotstar', 'Netflix', 'Netflix', 'Jio Cinema', 'Jio Cinema', 'Jio Cinema', 'Hotstar', 'VI movies and tv', 'Hotstar', 'Netflix', 'Netflix', 'Amazon Prime Video,Amazon Prime Video', 'Amazon Prime Video,Amazon Prime Video', '', 'Netflix,Crunchyroll Amazon Channel,Anime Times Amazon Channel', 'Netflix', 'Jio Cinema', 'Jio Cinema', 'Netflix', 'Netflix', 'Alt Balaji', 'Hotstar', 'Netflix', 'Hotstar', '', '', 'Jio Cinema', 'Zee5,VI movies and tv', 'Netflix', 'Hotstar', '', 'Apple TV Plus,Apple TV Plus', 'Amazon Prime Video,Amazon Prime Video', 'Alt Balaji', 'Hotstar', 'Netflix', 'Lionsgate Play,Lionsgate Play Apple TV Channel,Lionsgate Play Amazon Channel', 'Netflix', 'Netflix,Crunchyroll Amazon Channel', 'Jio Cinema', 'Amazon Prime Video,Amazon Prime Video', '', 'Netflix', 'Amazon Prime Video,Amazon Prime Video', 'Lionsgate Play', 'Amazon Prime Video,Amazon Prime Video', 'Netflix', 'Amazon Prime Video,Amazon Prime Video', 'Netflix,Jio Cinema,Crunchyroll Amazon Channel', 'Netflix', 'Netflix,Crunchyroll Amazon Channel,Anime Times Amazon Channel', 'Netflix', 'Sony Liv,VI movies and tv', 'Anime Times Amazon Channel', 'Apple TV Plus,Apple TV Plus', 'Zee5,VI movies and tv', 'Netflix', 'Netflix', 'Hotstar', 'Netflix,Crunchyroll Amazon Channel', 'Netflix', 'Hotstar', 'MX Player', 'Zee5', 'Anime Times Amazon Channel', 'Jio Cinema', 'Netflix', 'Zee5', 'Zee5', 'Amazon Prime Video,Amazon Prime Video', 'Amazon Prime Video,Amazon Prime Video', 'Amazon Prime Video,Amazon Prime Video,Netflix', 'Jio Cinema', 'Hotstar', 'Jio Cinema', 'Hoichoi,Hoichoi Amazon Channel', 'Amazon Prime Video,Netflix,Amazon Prime Video', 'Jio Cinema', 'Amazon Prime Video,Netflix,Amazon Prime Video,Jio Cinema', 'Jio Cinema', 'Netflix', 'Netflix,Anime Times Amazon Channel', 'Amazon Prime Video,Amazon Prime Video', 'Amazon Prime Video,Netflix,Amazon Prime Video', 'Amazon Prime Video,Netflix,Amazon Prime Video,Hotstar,Jio Cinema,Anime Times Amazon Channel', 'Netflix', 'Netflix', 'Netflix', 'Netflix', 'Hotstar', 'Amazon Prime Video,Netflix,Amazon Prime Video,Jio Cinema']

## **Fetching Duration Details**

In [ ]:
# Write Your Code here
tv_runtime = []
for url in tv_url:
  try:
    content = requests.get(url,headers = headers)
    soup = BeautifulSoup(content.text,'html.parser')
    for i in soup.find_all('div',class_ = 'detail-infos'):
      if i.find_all('h3')[0].text == 'Runtime':
        runtime = i.find_all('div')[0].text
  except:
    runtime = 'NA'
  tv_runtime.append(runtime)
print(tv_runtime)
print('The number of runtime :' , len(tv_runtime))

['51min', '58min', '50min', '32min', '50min', '50min', '22min', '45min', '1h 15min', '39min', '50min', '49min', '58min', '44min', '39min', '42min', '28min', '21min', '40min', '50min', '28min', '35min', '43min', '24min', '26min', '37min', '54min', '47min', '32min', '44min', '35min', '1h 0min', '43min', '21min', '44min', '1h 2min', '35min', '45min', '1h 5min', '45min', '46min', '1h 1min', '24min', '59min', '58min', '43min', '56min', '24min', '43min', '56min', '43min', '1h 11min', '42min', '54min', '1h 8min', '49min', '57min', '27min', '35min', '24min', '45min', '52min', '25min', '49min', '30min', '45min', '58min', '21min', '23min', '46min', '21min', '43min', '44min', '3min', '21min', '48min', '34min', '41min', '42min', '59min', '19min', '58min', '44min', '51min', '44min', '20min', '1h 1min', '44min', '49min', '58min', '23min', '55min', '42min', '24min', '1h 1min', '45min', '39min', '38min', '49min', '44min']
The number of runtime : 100

## **Creating TV Show DataFrame**

In [ ]:
# Write Your Code here

info = {'TV_URL' : tv_url, 'TV_Show_Name' : tv_show_title, 'Release_Year' : tv_year, 'Genres' : tv_genres, 'Runtime' : tv_runtime,
        'Age_Rating' : tv_age_rating, 'Production_Country' : tv_production_country, 'Rating' : imdb_rating , 'Stream_Service' : tv_stream_service }
data_tv = pd.DataFrame(info)
data_tv

,TV_URL,TV_Show_Name,Release_Year,Genres,Runtime,Age_Rating,Production_Country,Rating,Stream_Service
0,https://www.justwatch.com/in/tv-show/from,From (2022),2022,"Drama, Horror, Science-Fiction, Mystery & Thri...",51min,NA,United States,7.8,"Amazon Prime Video,Amazon Prime Video"
1,https://www.justwatch.com/in/tv-show/the-penguin,The Penguin (2024),2024,"Crime, Drama, Fantasy",58min,NA,United States,8.8,Jio Cinema
2,https://www.justwatch.com/in/tv-show/citadel-h...,Citadel: Honey Bunny (2024),2024,"Action & Adventure, Drama, Science-Fiction, My...",50min,NA,India,6.3,"Amazon Prime Video,Amazon Prime Video"
3,https://www.justwatch.com/in/tv-show/taaza-khabar,Taaza Khabar (2023),2023,"Science-Fiction, Drama, Fantasy, Mystery & Thr...",32min,NA,India,8.1,Hotstar
4,https://www.justwatch.com/in/tv-show/mirzapur,Mirzapur (2018),2018,"Action & Adventure, Drama, Mystery & Thriller,...",50min,A,India,8.4,"Amazon Prime Video,Amazon Prime Video"
...,...,...,...,...,...,...,...,...,...
95,https://www.justwatch.com/in/tv-show/vikings,Vikings (2013),2013,"War & Military, History, Romance, Action & Adv...",45min,A,Canada,8.5,Netflix
96,https://www.justwatch.com/in/tv-show/fabulous-...,Fabulous Lives of Bollywood Wives (2020),2020,"Reality TV, Documentary, Romance",39min,NA,India,4.2,Netflix
97,https://www.justwatch.com/in/tv-show/we-were-k...,We Were Kings (2024),2024,"Drama, Crime",38min,A,Mexico,5.1,Netflix
98,https://www.justwatch.com/in/tv-show/prison-break,Prison Break (2005),2005,"Action & Adventure, Crime, Drama, Mystery & Th...",49min,U,United States,8.3,Hotstar
99,https://www.justwatch.com/in/tv-show/suits,Suits (2011),2011,"Drama, Comedy",44min,NA,United States,8.4,"Amazon Prime Video,Netflix,Amazon Prime Video,..."

## **Task 2 :- Data Filtering & Analysis**

In [ ]:
# # Write Your Code here
# - Only include movies and TV shows released in the last 2 years (from the current date).
# - Only include movies and TV shows with an IMDb rating of 7 or higher.
# For movie
data_movie['Rating'] = data_movie['Rating'].replace('NA', float('NaN'))
data_movie['Release_Year'] = pd.to_datetime(data_movie['Release_Year'])
import datetime as dt
current_year = dt.datetime.now().year
rqr_year_rating = data_tv[(data_tv['Release_Year'].dt.year >= current_year) & (data_tv['Rating'].astype('float') >= 7.0)]
rqr_year_rating

,TV_URL,TV_Show_Name,Release_Year,Genres,Runtime,Age_Rating,Production_Country,Rating,Stream_Service
1,https://www.justwatch.com/in/tv-show/the-penguin,The Penguin (2024),2024-01-01,"Crime, Drama, Fantasy",58min,NA,United States,8.8,Jio Cinema
5,https://www.justwatch.com/in/tv-show/the-day-o...,The Day of the Jackal (2024),2024-01-01,"Crime, Drama, Mystery & Thriller, Action & Adv...",50min,NA,United Kingdom,8.1,Jio Cinema
7,https://www.justwatch.com/in/tv-show/dont-come...,Don't Come Home (2024),2024-01-01,"Mystery & Thriller, Drama, Horror, Science-Fic...",45min,NA,Thailand,7.3,Netflix
9,https://www.justwatch.com/in/tv-show/agatha-ho...,Agatha All Along (2024),2024-01-01,"Science-Fiction, Mystery & Thriller, Comedy, D...",39min,NA,United States,7.3,Hotstar
13,https://www.justwatch.com/in/tv-show/sweetpea,Sweetpea (2024),2024-01-01,"Comedy, Drama",44min,NA,United Kingdom,7.2,Jio Cinema
15,https://www.justwatch.com/in/tv-show/1000-babies,1000 Babies (2024),2024-01-01,"Crime, Drama, Horror",42min,A,India,7.2,Hotstar
23,https://www.justwatch.com/in/tv-show/dan-da-dan,Dan Da Dan (2024),2024-01-01,"Action & Adventure, Science-Fiction, Romance, ...",24min,NA,Japan,8.7,"Netflix,Crunchyroll Amazon Channel,Anime Times..."
24,https://www.justwatch.com/in/tv-show/nobody-wa...,Nobody Wants This (2024),2024-01-01,"Comedy, Romance, Drama",26min,NA,United States,7.9,Netflix
26,https://www.justwatch.com/in/tv-show/dune-the-...,Dune: Prophecy (2024),2024-01-01,"Drama, Science-Fiction, Action & Adventure",54min,NA,United States,7.5,Jio Cinema
28,https://www.justwatch.com/in/tv-show/murder-mi...,Murder Mindfully (2024),2024-01-01,"Comedy, Crime, Mystery & Thriller",32min,A,Germany,7.5,Netflix
32,https://www.justwatch.com/in/tv-show/say-nothing,Say Nothing (2024),2024-01-01,"Drama, Crime, History, Mystery & Thriller",43min,NA,United States,8.4,Hotstar
33,https://www.justwatch.com/in/tv-show/georgie-a...,Georgie & Mandy's First Marriage (2024),2024-01-01,Comedy,21min,NA,United States,8.4,
37,https://www.justwatch.com/in/tv-show/kill-me-l...,Kill Me Love Me (2024),2024-01-01,"Drama, Action & Adventure",45min,NA,China,7.4,Netflix
38,https://www.justwatch.com/in/tv-show/the-judge...,The Judge from Hell (2024),2024-01-01,"Comedy, Drama, Science-Fiction, Crime, Romance...",1h 5min,NA,South Korea,7.9,Hotstar
43,https://www.justwatch.com/in/tv-show/shogun-2024,Shōgun (2024),2024-01-01,"War & Military, History, Drama",59min,NA,United States,8.6,Hotstar
47,https://www.justwatch.com/in/tv-show/dragon-ba...,Dragon Ball DAIMA (2024),2024-01-01,"Animation, Action & Adventure, Comedy, Science...",24min,NA,Japan,8.1,"Netflix,Crunchyroll Amazon Channel"
48,https://www.justwatch.com/in/tv-show/murder-in...,Murder in Mahim (2024),2024-01-01,Crime,43min,NA,India,7.8,Jio Cinema
50,https://www.justwatch.com/in/tv-show/high-pote...,High Potential (2024),2024-01-01,"Crime, Drama",43min,NA,United States,8.3,
51,https://www.justwatch.com/in/tv-show/doubt-2024,Doubt (2024),2024-01-01,"Crime, Mystery & Thriller, Drama",1h 11min,NA,South Korea,8.3,Netflix
56,https://www.justwatch.com/in/tv-show/cross,Cross (2024),2024-01-01,"Mystery & Thriller, Action & Adventure, Crime,...",57min,NA,United States,7.2,"Amazon Prime Video,Amazon Prime Video"
60,https://www.justwatch.com/in/tv-show/this-is-t...,This Is the Zodiac Speaking (2024),2024-01-01,"Documentary, Crime",45min,NA,United States,7.2,Netflix
63,https://www.justwatch.com/in/tv-show/disclaimer,Disclaimer (2024),2024-01-01,"Drama, Mystery & Thriller",49min,A,United Kingdom,7.5,"Apple TV Plus,Apple TV Plus"
69,https://www.justwatch.com/in/tv-show/raising-v...,Raising Voices (2024),2024-01-01,Drama,46min,A,Spain,7.2,Netflix
72,https://www.justwatch.com/in/tv-show/gyaarah-g...,Gyaarah Gyaarah (2024),2024-01-01,"Drama, Fantasy, Science-Fiction",44min,A,India,8.2,Zee5
76,https://www.justwatch.com/in/tv-show/murshid,Murshid (2024),2024-01-01,"Crime, Mystery & Thriller",34min,A,India,7.4,Zee5
77,https://www.justwatch.com/in/tv-show/aindham-v...,Aindham Vedham (2024),2024-01-01,Mystery & Thriller,41min,NA,India,7.5,Zee5

In [ ]:
# For TV show
data_tv['Rating'] = data_tv['Rating'].replace('NA', float('NaN'))
data_tv['Release_Year'] = pd.to_datetime(data_tv['Release_Year'])
import datetime as dt
current_year = dt.datetime.now().year
rqr_year_rating = data_tv[(data_tv['Release_Year'].dt.year >= current_year - 2) & (data_tv['Rating'].astype('float') >= 7.0 )]
rqr_year_rating

,TV_URL,TV_Show_Name,Release_Year,Genres,Runtime,Age_Rating,Production_Country,Rating,Stream_Service
0,https://www.justwatch.com/in/tv-show/from,From (2022),2022-01-01,"Drama, Horror, Science-Fiction, Mystery & Thri...",51min,NA,United States,7.8,"Amazon Prime Video,Amazon Prime Video"
1,https://www.justwatch.com/in/tv-show/the-penguin,The Penguin (2024),2024-01-01,"Crime, Drama, Fantasy",58min,NA,United States,8.8,Jio Cinema
3,https://www.justwatch.com/in/tv-show/taaza-khabar,Taaza Khabar (2023),2023-01-01,"Science-Fiction, Drama, Fantasy, Mystery & Thr...",32min,NA,India,8.1,Hotstar
5,https://www.justwatch.com/in/tv-show/the-day-o...,The Day of the Jackal (2024),2024-01-01,"Crime, Drama, Mystery & Thriller, Action & Adv...",50min,NA,United Kingdom,8.1,Jio Cinema
7,https://www.justwatch.com/in/tv-show/dont-come...,Don't Come Home (2024),2024-01-01,"Mystery & Thriller, Drama, Horror, Science-Fic...",45min,NA,Thailand,7.3,Netflix
9,https://www.justwatch.com/in/tv-show/agatha-ho...,Agatha All Along (2024),2024-01-01,"Science-Fiction, Mystery & Thriller, Comedy, D...",39min,NA,United States,7.3,Hotstar
11,https://www.justwatch.com/in/tv-show/the-diplomat,The Diplomat (2023),2023-01-01,"Drama, War & Military, Mystery & Thriller",49min,A,United States,8.0,Netflix
13,https://www.justwatch.com/in/tv-show/sweetpea,Sweetpea (2024),2024-01-01,"Comedy, Drama",44min,NA,United Kingdom,7.2,Jio Cinema
14,https://www.justwatch.com/in/tv-show/tulsa-king,Tulsa King (2022),2022-01-01,"Drama, Crime",39min,NA,United States,8.0,Jio Cinema
15,https://www.justwatch.com/in/tv-show/1000-babies,1000 Babies (2024),2024-01-01,"Crime, Drama, Horror",42min,A,India,7.2,Hotstar
23,https://www.justwatch.com/in/tv-show/dan-da-dan,Dan Da Dan (2024),2024-01-01,"Action & Adventure, Science-Fiction, Romance, ...",24min,NA,Japan,8.7,"Netflix,Crunchyroll Amazon Channel,Anime Times..."
24,https://www.justwatch.com/in/tv-show/nobody-wa...,Nobody Wants This (2024),2024-01-01,"Comedy, Romance, Drama",26min,NA,United States,7.9,Netflix
26,https://www.justwatch.com/in/tv-show/dune-the-...,Dune: Prophecy (2024),2024-01-01,"Drama, Science-Fiction, Action & Adventure",54min,NA,United States,7.5,Jio Cinema
28,https://www.justwatch.com/in/tv-show/murder-mi...,Murder Mindfully (2024),2024-01-01,"Comedy, Crime, Mystery & Thriller",32min,A,Germany,7.5,Netflix
32,https://www.justwatch.com/in/tv-show/say-nothing,Say Nothing (2024),2024-01-01,"Drama, Crime, History, Mystery & Thriller",43min,NA,United States,8.4,Hotstar
33,https://www.justwatch.com/in/tv-show/georgie-a...,Georgie & Mandy's First Marriage (2024),2024-01-01,Comedy,21min,NA,United States,8.4,
35,https://www.justwatch.com/in/tv-show/house-of-...,House of the Dragon (2022),2022-01-01,"Science-Fiction, Drama, Action & Adventure, Fa...",1h 2min,A,United States,8.3,Jio Cinema
36,https://www.justwatch.com/in/tv-show/mithya,Mithya (2022),2022-01-01,"Drama, Crime, Mystery & Thriller",35min,NA,India,7.7,"Zee5,VI movies and tv"
37,https://www.justwatch.com/in/tv-show/kill-me-l...,Kill Me Love Me (2024),2024-01-01,"Drama, Action & Adventure",45min,NA,China,7.4,Netflix
38,https://www.justwatch.com/in/tv-show/the-judge...,The Judge from Hell (2024),2024-01-01,"Comedy, Drama, Science-Fiction, Crime, Romance...",1h 5min,NA,South Korea,7.9,Hotstar
39,https://www.justwatch.com/in/tv-show/special-o...,Lioness (2023),2023-01-01,"Drama, War & Military, Action & Adventure, Mys...",45min,NA,United States,7.9,
40,https://www.justwatch.com/in/tv-show/silo,Silo (2023),2023-01-01,"Drama, Science-Fiction",46min,A,United States,8.1,"Apple TV Plus,Apple TV Plus"
43,https://www.justwatch.com/in/tv-show/shogun-2024,Shōgun (2024),2024-01-01,"War & Military, History, Drama",59min,NA,United States,8.6,Hotstar
47,https://www.justwatch.com/in/tv-show/dragon-ba...,Dragon Ball DAIMA (2024),2024-01-01,"Animation, Action & Adventure, Comedy, Science...",24min,NA,Japan,8.1,"Netflix,Crunchyroll Amazon Channel"
48,https://www.justwatch.com/in/tv-show/murder-in...,Murder in Mahim (2024),2024-01-01,Crime,43min,NA,India,7.8,Jio Cinema
49,https://www.justwatch.com/in/tv-show/farzi,Farzi (2023),2023-01-01,"Drama, Crime, Mystery & Thriller",56min,NA,India,8.3,"Amazon Prime Video,Amazon Prime Video"
50,https://www.justwatch.com/in/tv-show/high-pote...,High Potential (2024),2024-01-01,"Crime, Drama",43min,NA,United States,8.3,
51,https://www.justwatch.com/in/tv-show/doubt-2024,Doubt (2024),2024-01-01,"Crime, Mystery & Thriller, Drama",1h 11min,NA,South Korea,8.3,Netflix
55,https://www.justwatch.com/in/tv-show/the-linco...,The Lincoln Lawyer (2022),2022-01-01,"Mystery & Thriller, Crime, Drama",49min,NA,United States,7.8,Netflix
56,https://www.justwatch.com/in/tv-show/cross,Cross (2024),2024-01-01,"Mystery & Thriller, Action & Adventure, Crime,...",57min,NA,United States,7.2,"Amazon Prime Video,Amazon Prime Video"
60,https://www.justwatch.com/in/tv-show/this-is-t...,This Is the Zodiac Speaking (2024),2024-01-01,"Documentary, Crime",45min,NA,United States,7.2,Netflix
63,https://www.justwatch.com/in/tv-show/disclaimer,Disclaimer (2024),2024-01-01,"Drama, Mystery & Thriller",49min,A,United Kingdom,7.5,"Apple TV Plus,Apple TV Plus"
69,https://www.justwatch.com/in/tv-show/raising-v...,Raising Voices (2024),2024-01-01,Drama,46min,A,Spain,7.2,Netflix
72,https://www.justwatch.com/in/tv-show/gyaarah-g...,Gyaarah Gyaarah (2024),2024-01-01,"Drama, Fantasy, Science-Fiction",44min,A,India,8.2,Zee5
76,https://www.justwatch.com/in/tv-show/murshid,Murshid (2024),2024-01-01,"Crime, Mystery & Thriller",34min,A,India,7.4,Zee5
77,https://www.justwatch.com/in/tv-show/aindham-v...,Aindham Vedham (2024),2024-01-01,Mystery & Thriller,41min,NA,India,7.5,Zee5
79,https://www.justwatch.com/in/tv-show/the-devil...,The Devil's Hour (2022),2022-01-01,"Mystery & Thriller, Crime, Drama",59min,NA,United Kingdom,7.6,"Amazon Prime Video,Amazon Prime Video"
91,https://www.justwatch.com/in/tv-show/the-walki...,The Walking Dead: Daryl Dixon (2023),2023-01-01,"Science-Fiction, Action & Adventure, Drama, Ho...",55min,NA,United States,7.5,"Amazon Prime Video,Amazon Prime Video"
93,https://www.justwatch.com/in/tv-show/bleach-th...,Bleach: Thousand-Year Blood War (2022),2022-01-01,"Fantasy, Animation, Action & Adventure",24min,NA,Japan,9.0,"Amazon Prime Video,Netflix,Amazon Prime Video,..."

## **Calculating Mean IMDB Ratings for both Movies and Tv Shows**

In [ ]:
# Write Your Code here
# Calculate the average IMDb rating for the scraped movies and TV shows
# for movie
data_movie['Rating'].astype("float").mean().round(2)

6.89

In [ ]:
# for tv
data_tv['Rating'].astype('float').mean().round(2)

7.82

## **Analyzing Top Genres**

In [ ]:
# Identify the top 5 genres that have the highest number of available movies and TV shows
# for movie
movie_genres_count = data_movie['Genres'].value_counts().sort_values(ascending = False)
movie_top5_genres = movie_genres_count.head(5)
movie_top5_genres

Genres
Drama                                                      5
Crime, Drama, Mystery & Thriller, Action & Adventure       4
Action & Adventure, Drama, Mystery & Thriller              4
Comedy, Horror                                             3
Action & Adventure, Science-Fiction, Mystery & Thriller    3
Name: count, dtype: int64

In [ ]:
# for tv
tv_genres_count = data_tv['Genres'].value_counts().sort_values(ascending = False)
tv_top5_genres = tv_genres_count.head(5)
tv_top5_genres

Genres
Drama, Crime, Mystery & Thriller    4
Drama                               4
Drama, Mystery & Thriller, Crime    3
Comedy                              3
Drama, Crime                        3
Name: count, dtype: int64

In [ ]:
#Let's Visvalize it using word cloud

## **Finding Predominant Streaming Service**

In [ ]:
# Write Your Code here
# Determine the streaming service with the most significant number of offerings.
# for movie
movie_stream_service_count = data_movie['Stream_Service'].value_counts().sort_values(ascending = False)
movie_most_number_of_stream_service = movie_stream_service_count.head(5)
movie_most_number_of_stream_service

Stream_Service
Netflix                                  13
Bookmyshow                               11
Amazon Prime Video,Amazon Prime Video     9
Hotstar                                   6
                                          6
Name: count, dtype: int64

In [ ]:
# for tv
tv_stream_service_count = data_tv['Stream_Service'].value_counts().sort_values(ascending=False)
tv_most_number_of_stream_service = tv_stream_service_count.head(5)
tv_most_number_of_stream_service

Stream_Service
Netflix                                  25
Jio Cinema                               14
Amazon Prime Video,Amazon Prime Video    13
Hotstar                                  13
                                          5
Name: count, dtype: int64

## **Task 3 :- Data Export**

In [ ]:
#saving final dataframe as Final Data in csv format
# for movie
data_movie.to_csv('data_movie.csv')

In [ ]:

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
data_movie = '/content/data_movie.csv'

In [ ]:
# for tv
data_tv.to_csv('data_tv.csv')

In [ ]:
data_tv = '/content/data_tv.csv'

# **Dataset Drive Link (View Access with Anyone) -**


https://colab.research.google.com/drive/12fXWxjY0HFr1m_HkPxCe_TphAsB-lfFq?usp=sharing

# ***Congratulations!!! You have completed your Assignment.***